ITEM_MAPPING = {
	-- [66001] = {{"Bombs"}, "consumable"}, -- Bombs(5)
	-- [66002] = {{"DekuNuts"}, "consumable"}, -- DekuNuts(5)
	[66003] = {{"Bombchus"}, "toggle"}, -- Bombchus(10)
	[66006] = {{"Boomerang"}, "toggle"},
	-- [66007] = {{"DekuStick"}, "consumable"}, -- DekuStick(1)
	[66010] = {{"LensofTruth"}, "toggle"},
	[66013] = {{"MegatonHammer"}, "toggle"},
	[66014] = {{"AdultTrade", "Cojiro"}, "progressive_toggle"},
	[66015] = {{"Bottle"}, "consumable"},
	[66020] = {{"Bottle"}, "consumable"}, -- BottlewithMilk
	[66021] = {{"Bottle", "RutosLetter"}, "toggle"},
	[66022] = {{"MagicBean"}, "consumable"},
	[66029] = {{"AdultTrade", "PocketEgg"}, "progressive_toggle"},
	[66030] = {{"AdultTrade", "PocketCucco"}, "progressive_toggle"},
	[66031] = {{"AdultTrade", "OddMushroom"}, "progressive_toggle"},
	[66032] = {{"AdultTrade", "OddPotion"}, "progressive_toggle"},
	[66033] = {{"AdultTrade", "PoachersSaw"}, "progressive_toggle"},
	[66034] = {{"AdultTrade", "BrokenSword"}, "progressive_toggle"},
	[66035] = {{"AdultTrade", "Prescription"}, "progressive_toggle"},
	[66036] = {{"AdultTrade", "EyeballFrog"}, "progressive_toggle"},
	[66037] = {{"AdultTrade", "Eyedrops"}, "progressive_toggle"},
	[66038] = {{"AdultTrade", "ClaimCheck"}, "progressive_toggle"},
	[66039] = {{"KokiriSword"}, "toggle"},
	[66040] = {{"GiantsKnife"}, "toggle"},
	[66041] = {{"DekuShield"}, "toggle"},
	[66042] = {{"HylianShield"}, "toggle"},
	[66043] = {{"MirrorShield"}, "toggle"},
	[66044] = {{"GoronTunic"}, "toggle"},
	[66045] = {{"ZoraTunic"}, "toggle"},
	[66046] = {{"IronBoots"}, "toggle"},
	[66047] = {{"HoverBoots"}, "toggle"},
	[66057] = {{"StoneofAgony"}, "toggle"},
	[66058] = {{"GerudoMembershipCard"}, "toggle"},
	[66061] = {{"HeartContainer"}, "consumable"},
	[66062] = {{"PieceofHeart"}, "consumable"},
	[66071] = {{"WeirdEgg"}, "toggle"},
	[66072] = {{"RecoveryHeart"}, "toggle"},
	-- [66073] = {"Arrows(5)", "consumable"}, -- Arrows(5)
	-- [66074] = {"Arrows(10)", "consumable"}, -- Arrows(10)
	-- [66075] = {"Arrows(30)", "consumable"}, -- Arrows(30)
	-- [66076] = {"Rupee(1)", "consumable"}, -- Rupees(1)
	-- [66077] = {"Rupees(5)", "consumable"}, -- Rupees(5)
	-- [66078] = {"Rupees(20)", "consumable"}, -- Rupees(20)
	-- [66085] = {"Rupees(50)", "consumable"}, -- Rupees(50)
	-- [66086] = {"Rupees(200)", "consumable"}, -- Rupees(200)
	[66087] = {{"BiggoronSword"}, "toggle"},
	[66088] = {{"FireArrows"}, "toggle"},
	[66089] = {{"IceArrows"}, "toggle"},
	[66090] = {{"LightArrows"}, "toggle"},
	[66091] = {{"GoldSkulltulaToken"}, "consumable"},
	[66092] = {{"DinsFire"}, "toggle"},
	[66094] = {{"NayrusLove"}, "toggle"},
	[66093] = {{"FaroresWind"}, "toggle"},
	-- [66100] = {{"DekuNuts"}, "consumable"}, -- DekuNuts(10)
	-- [66102] = {{"Bombs"}, "consumable"}, -- Bombs(10)
	-- [66103] = {{"Bombs"}, "consumable"}, -- Bombs(20)
	-- [66105] = {{"DekuSeeds"}, "consumable"}, -- DekuSeeds(30)
	[66106] = {{"Bombchus"}, "toggle"}, -- Bombchus(5)
	[66107] = {{"Bombchus"}, "toggle"}, -- Bombchus(20)
	-- [66114] = {{"Rupee"}, "consumable"}, -- (TreasureChestGame)
	[66118] = {{"PieceofHeart"}, "consumable"},  -- (TreasureChestGame)
	[66124] = {{"IceTrap"}, "consumable"},
	[66128] = {{"ProgressiveHookshot"}, "progressive"},
	[66129] = {{"ProgressiveStrengthUpgrade"}, "progressive"},
	[66130] = {{"Bombs"}, "toggle"}, --bombbag
	[66131] = {{"Bow"}, "toggle"},
	[66132] = {{"Slingshot"}, "toggle"},
	[66133] = {{"ProgressiveWallet"}, "progressive"},
	[66134] = {{"ProgressiveScale"}, "progressive"},
	[66135] = {{"DekuNuts"}, "toggle"}, --capacity upgrades
	[66136] = {{"DekuStick"}, "toggle"}, --capacity upgrades
	[66137] = {{"Bombchus"}, "toggle"},
	[66138] = {{"MagicMeter"}, "progressive"},
	[66139] = {{"Ocarina"}, "progressive"},
	[66140] = {{"Bottle"}, "consumable"}, -- BottlewithRedPotion
	[66141] = {{"Bottle"}, "consumable"}, -- BottlewithGreenPotion
	[66142] = {{"Bottle"}, "consumable"}, -- BottlewithBluePotion
	[66143] = {{"Bottle"}, "consumable"}, -- BottlewithFairy
	[66144] = {{"Bottle"}, "consumable"}, -- BottlewithFish
	[66145] = {{"Bottle"}, "consumable"}, -- BottlewithBlueFire
	[66146] = {{"Bottle"}, "consumable"}, -- BottlewithBugs
	[66147] = {{"Bottle"}, "consumable"}, -- BottlewithBigPoe
	[66148] = {{"Bottle"}, "consumable"}, -- BottlewithPoe
	[66149] = {{"BossKey(ForestTemple)"}, "toggle"},
	[66150] = {{"BossKey(FireTemple)"}, "toggle"},
	[66151] = {{"BossKey(WaterTemple)"}, "toggle"},
	[66152] = {{"BossKey(SpiritTemple)"}, "toggle"},
	[66153] = {{"BossKey(ShadowTemple)"}, "toggle"},
	[66154] = {{"BossKey(GanonsCastle)"}, "toggle"},
	[66155] = {{"Compass(DekuTree)"}, "toggle"},
	[66156] = {{"Compass(DodongosCavern)"}, "toggle"},
	[66157] = {{"Compass(JabuJabusBelly)"}, "toggle"},
	[66158] = {{"Compass(ForestTemple)"}, "toggle"},
	[66159] = {{"Compass(FireTemple)"}, "toggle"},
	[66160] = {{"Compass(WaterTemple)"}, "toggle"},
	[66161] = {{"Compass(SpiritTemple)"}, "toggle"},
	[66162] = {{"Compass(ShadowTemple)"}, "toggle"},
	[66163] = {{"Compass(BottomoftheWell)"}, "toggle"},
	[66164] = {{"Compass(IceCavern)"}, "toggle"},
	[66165] = {{"Map(DekuTree)"}, "toggle"},
	[66166] = {{"Map(DodongosCavern)"}, "toggle"},
	[66167] = {{"Map(JabuJabusBelly)"}, "toggle"},
	[66168] = {{"Map(ForestTemple)"}, "toggle"},
	[66169] = {{"Map(FireTemple)"}, "toggle"},
	[66170] = {{"Map(WaterTemple)"}, "toggle"},
	[66171] = {{"Map(SpiritTemple)"}, "toggle"},
	[66172] = {{"Map(ShadowTemple)"}, "toggle"},
	[66173] = {{"Map(BottomoftheWell)"}, "toggle"},
	[66174] = {{"Map(IceCavern)"}, "toggle"},
	[66175] = {{"SmallKey(ForestTemple)", "MQSmallKey(ForestTemple)"}, "consumable"},
	[66176] = {{"SmallKey(FireTemple)", "MQSmallKey(FireTemple)"}, "consumable"},
	[66177] = {{"SmallKey(WaterTemple)", "MQSmallKey(WaterTemple)"}, "consumable"},
	[66178] = {{"SmallKey(SpiritTemple)", "MQSmallKey(SpiritTemple)"}, "consumable"},
	[66179] = {{"SmallKey(ShadowTemple)", "MQSmallKey(ShadowTemple)"}, "consumable"},
	[66180] = {{"SmallKey(BottomoftheWell)", "MQSmallKey(BottomoftheWell)"}, "consumable"},
	[66181] = {{"SmallKey(GerudoTrainingGround)", "MQSmallKey(GerudoTrainingGround)"}, "consumable"},
	[66182] = {{"SmallKey(ThievesHideout)", "MQSmallKey(ThievesHideout)"}, "consumable"},
	[66183] = {{"SmallKey(GanonsCastle)", "MQSmallKey(GanonsCastle)"}, "consumable"},
	-- [66184] = {{"DoubleDefense"}, "toggle"},
	[66201] = {{"MagicBeanPack", "MagicBean", "MagicBean", "MagicBean", "MagicBean", "MagicBean", "MagicBean", "MagicBean", "MagicBean", "MagicBean", "MagicBean"}, "consumable"},
	[66202] = {{"TriforcePiece"}, "consumable"},
	[66011] = {{"ZeldasLetter"}, "toggle"},
	[66187] = {{"MinuetofForest"}, "toggle"},
	[66188] = {{"BoleroofFire"}, "toggle"},
	[66189] = {{"SerenadeofWater"}, "toggle"},
	[66190] = {{"RequiemofSpirit"}, "toggle"},
	[66191] = {{"NocturneofShadow"}, "toggle"},
	[66192] = {{"PreludeofLight"}, "toggle"},
	[66193] = {{"ZeldasLullaby"}, "toggle"},
	[66194] = {{"EponasSong"}, "toggle"},
	[66195] = {{"SariasSong"}, "toggle"},
	[66196] = {{"SunsSong"}, "toggle"},
	[66197] = {{"SongofTime"}, "toggle"},
	[66198] = {{"SongofStorms"}, "toggle"},
	[66203] = {{"SmallKeyRing(ForestTemple)"}, "toggle"},
	[66204] = {{"SmallKeyRing(FireTemple)"}, "toggle"},
	[66205] = {{"SmallKeyRing(WaterTemple)"}, "toggle"},
	[66206] = {{"SmallKeyRing(SpiritTemple)"}, "toggle"},
	[66207] = {{"SmallKeyRing(ShadowTemple)"}, "toggle"},
	[66208] = {{"SmallKeyRing(BottomoftheWell)"}, "toggle"},
	[66209] = {{"SmallKeyRing(GerudoTrainingGround)"}, "toggle"},
	[66210] = {{"SmallKeyRing(ThievesHideout)"}, "toggle"},
	[66211] = {{"SmallKeyRing(GanonsCastle)"}, "toggle"},
}