--Colossus
Child_Desert_Colossus = OOTLocation.new("Child_Desert_Colossus")
Child_Colossus_Great_Fairy_Fountain = OOTLocation.new("Child_Colossus_Great_Fairy_Fountain")
Child_Colossus_Grotto = OOTLocation.new("Child_Colossus_Grotto")
Child_Desert_Colossus_From_Spirit_Lobby = OOTLocation.new("Child_Desert_Colossus_From_Spirit_Lobby")

Adult_Desert_Colossus = OOTLocation.new("Adult_Desert_Colossus")
Adult_Colossus_Great_Fairy_Fountain = OOTLocation.new("Adult_Colossus_Great_Fairy_Fountain")
Adult_Colossus_Grotto = OOTLocation.new("Adult_Colossus_Grotto")
Adult_Desert_Colossus_From_Spirit_Lobby = OOTLocation.new("Adult_Desert_Colossus_From_Spirit_Lobby")
--ZR
Child_ZR_Front = OOTLocation.new("Child_ZR_Front")
Child_Zora_River = OOTLocation.new("Child_Zora_River")
Child_ZR_Behind_Waterfall = OOTLocation.new("Child_ZR_Behind_Waterfall")
Child_ZR_Top_of_Waterfall = OOTLocation.new("Child_ZR_Top_of_Waterfall")
Child_ZR_Open_Grotto = OOTLocation.new("Child_ZR_Open_Grotto")
Child_ZR_Fairy_Grotto = OOTLocation.new("Child_ZR_Fairy_Grotto")
Child_ZR_Storms_Grotto = OOTLocation.new("Child_ZR_Storms_Grotto")

Adult_ZR_Front = OOTLocation.new("Adult_ZR_Front")
Adult_Zora_River = OOTLocation.new("Adult_Zora_River")
Adult_ZR_Behind_Waterfall = OOTLocation.new("Adult_ZR_Behind_Waterfall")
Adult_ZR_Top_of_Waterfall = OOTLocation.new("Adult_ZR_Top_of_Waterfall")
Adult_ZR_Open_Grotto = OOTLocation.new("Adult_ZR_Open_Grotto")
Adult_ZR_Fairy_Grotto = OOTLocation.new("Adult_ZR_Fairy_Grotto")
Adult_ZR_Storms_Grotto = OOTLocation.new("Adult_ZR_Storms_Grotto")
--ZF
Child_Zoras_Fountain = OOTLocation.new("Child_Zoras_Fountain")
Child_ZF_Underwater = OOTLocation.new("Child_ZF_Underwater")
Child_ZF_Hidden_Cave = OOTLocation.new("Child_ZF_Hidden_Cave")
Child_ZF_Ice_Ledge = OOTLocation.new("Child_ZF_Ice_Ledge")
Child_ZF_Great_Fairy_Fountain = OOTLocation.new("Child_ZF_Great_Fairy_Fountain")

Adult_Zoras_Fountain = OOTLocation.new("Adult_Zoras_Fountain")
Adult_ZF_Underwater = OOTLocation.new("Adult_ZF_Underwater")
Adult_ZF_Hidden_Cave = OOTLocation.new("Adult_ZF_Hidden_Cave")
Adult_ZF_Ice_Ledge = OOTLocation.new("Adult_ZF_Ice_Ledge")
Adult_ZF_Great_Fairy_Fountain = OOTLocation.new("Adult_ZF_Great_Fairy_Fountain")
--ZD
Child_Zoras_Domain = OOTLocation.new("Child_Zoras_Domain")
Child_ZD_Behind_King_Zora = OOTLocation.new("Child_ZD_Behind_King_Zora")
Child_ZD_Eyeball_Frog_Timeout = OOTLocation.new("Child_ZD_Eyeball_Frog_Timeout")
Child_ZD_Shop = OOTLocation.new("Child_ZD_Shop")
Child_ZD_Storms_Grotto = OOTLocation.new("Child_ZD_Storms_Grotto")

Adult_Zoras_Domain = OOTLocation.new("Adult_Zoras_Domain")
Adult_ZD_Behind_King_Zora = OOTLocation.new("Adult_ZD_Behind_King_Zora")
Adult_ZD_Eyeball_Frog_Timeout = OOTLocation.new("Adult_ZD_Eyeball_Frog_Timeout")
Adult_ZD_Shop = OOTLocation.new("Adult_ZD_Shop")
Adult_ZD_Storms_Grotto = OOTLocation.new("Adult_ZD_Storms_Grotto")
-- Wastelands
Child_Haunted_Wasteland = OOTLocation.new("Child_Haunted_Wastelands")
Child_Wasteland_Near_Fortress = OOTLocation.new("Child_Wasteland_Near_Fortress")
Child_Wasteland_Near_Crate = OOTLocation.new("Child_Wasteland_Near_Crate")
Child_Wasteland_Near_Colossus = OOTLocation.new("Child_Wasteland_Near_Colossus")

Adult_Haunted_Wasteland = OOTLocation.new("Adult_Haunted_Wastelands")
Adult_Wasteland_Near_Fortress = OOTLocation.new("Adult_Wasteland_Near_Fortress")
Adult_Wasteland_Near_Crate = OOTLocation.new("Adult_Wasteland_Near_Crate")
Adult_Wasteland_Near_Colossus = OOTLocation.new("Adult_Wasteland_Near_Colossus")
--ToT
Child_ToT_Entrance = OOTLocation.new("Child_ToT_Entrance")
Child_Temple_of_Time = OOTLocation.new("Child_Temple_of_Time")
Child_Beyond_Door_of_Time = OOTLocation.new("Child_Beyond_Door_of_Time")

Adult_ToT_Entrance = OOTLocation.new("Adult_ToT_Entrance")
Adult_Temple_of_Time = OOTLocation.new("Adult_Temple_of_Time")
Adult_Beyond_Door_of_Time = OOTLocation.new("Adult_Beyond_Door_of_Time")
--SFM
Child_Sacret_Forest_Meadow_Entryway = OOTLocation.new("Child_Sacret_Forest_Meadow_Entryway")
Child_Sacret_Forest_Meadow = OOTLocation.new("Child_Sacret_Forest_Meadow")
Child_SFM_Wolfos_Grotto = OOTLocation.new("Child_SFM_Wolfos_Grotto")
Child_SFM_Forest_Temple_Entrance_Ledge = OOTLocation.new("Child_SFM_Forest_Temple_Entrance_Ledge")
Child_SFM_Fairy_Grotto = OOTLocation.new("Child_SFM_Fairy_Grotto")
Child_SFM_Storms_Grotto = OOTLocation.new("Child_SFM_Storms_Grotto")

Adult_Sacret_Forest_Meadow_Entryway = OOTLocation.new("Adult_Sacret_Forest_Meadow_Entryway")
Adult_Sacret_Forest_Meadow = OOTLocation.new("Adult_Sacret_Forest_Meadow")
Adult_SFM_Wolfos_Grotto = OOTLocation.new("Adult_SFM_Wolfos_Grotto")
Adult_SFM_Forest_Temple_Entrance_Ledge = OOTLocation.new("Adult_SFM_Forest_Temple_Entrance_Ledge")
Adult_SFM_Fairy_Grotto = OOTLocation.new("Adult_SFM_Fairy_Grotto")
Adult_SFM_Storms_Grotto = OOTLocation.new("Adult_SFM_Storms_Grotto")
--Market
Child_Market_Entrance = OOTLocation.new("Child_Market_Entrance")
Child_Market = OOTLocation.new("Child_Market")
Child_Market_Back_Alley = OOTLocation.new("Child_Market_Back_Alley")
Child_Market_Guard_House = OOTLocation.new("Child_Market_Guard_House")
Child_Market_Bazaar = OOTLocation.new("Child_Market_Bazaar")
Child_Market_Mask_Shop = OOTLocation.new("Child_Market_Mask_Shop")
Child_Market_Shooting_Gallery = OOTLocation.new("Child_Market_Shooting_Gallery")
Child_Market_Bomchu_Bowling = OOTLocation.new("Child_Market_Bomchu_Bowling")
Child_Market_Potion_Shop = OOTLocation.new("Child_Market_Potion_Shop")
Child_Market_Treasure_Chest_Game = OOTLocation.new("Child_Market_Treasure_Chest_Game")
Child_Market_Bombchu_Shop = OOTLocation.new("Child_Market_Bombchu_Shop")
Child_Market_Dog_Lady_House = OOTLocation.new("Child_Market_Dog_Lady_House")
Child_Market_Man_in_Green_House = OOTLocation.new("Child_Market_Man_in_Green_House")

Adult_Market_Entrance = OOTLocation.new("Adult_Market_Entrance")
Adult_Market = OOTLocation.new("Adult_Market")
Adult_Market_Back_Alley = OOTLocation.new("Adult_Market_Back_Alley")
Adult_Market_Guard_House = OOTLocation.new("Adult_Market_Guard_House")
Adult_Market_Bazaar = OOTLocation.new("Adult_Market_Bazaar")
Adult_Market_Mask_Shop = OOTLocation.new("Adult_Market_Mask_Shop")
Adult_Market_Shooting_Gallery = OOTLocation.new("Adult_Market_Shooting_Gallery")
Adult_Market_Bomchu_Bowling = OOTLocation.new("Adult_Market_Bomchu_Bowling")
Adult_Market_Potion_Shop = OOTLocation.new("Adult_Market_Potion_Shop")
Adult_Market_Treasure_Chest_Game = OOTLocation.new("Adult_Market_Treasure_Chest_Game")
Adult_Market_Bombchu_Shop = OOTLocation.new("Adult_Market_Bombchu_Shop")
Adult_Market_Dog_Lady_House = OOTLocation.new("Adult_Market_Dog_Lady_House")
Adult_Market_Man_in_Green_House = OOTLocation.new("Adult_Market_Man_in_Green_House")
--LW
Child_Lost_Woods = OOTLocation.new("Child_Lost_Woods")
Child_LW_Beyond_Mido = OOTLocation.new("Child_LW_Beyond_Mido")
Child_LW_Bridge_From_Forest = OOTLocation.new("Child_LW_Bridge_From_Forest")
Child_LW_Forest_Exit = OOTLocation.new("Child_LW_Forest_Exit")
Child_GC_Woods_Warp = OOTLocation.new("Child_GC_Woods_Warp")
Child_LW_Bridge = OOTLocation.new("Child_LW_Bridge")
Child_LW_Underwater_Entrance = OOTLocation.new("Child_LW_Underwater_Entrance")
Child_Zora_River = OOTLocation.new("Child_Zora_River")
Child_LW_Near_Shortcuts_Grotto = OOTLocation.new("Child_LW_Near_Shortcuts_Grotto")
Child_Deku_Theater = OOTLocation.new("Child_Deku_Theater")
Child_LW_Scrubs_Grotto = OOTLocation.new("Child_LW_Scrubs_Grotto")

-- Child_LW_Near_Shortcuts_Grotto = OOTLocation.new("Child_LW_Near_Shortcuts_Grotto")

Adult_Lost_Woods = OOTLocation.new("Adult_Lost_Woods")
Adult_LW_Beyond_Mido = OOTLocation.new("Adult_LW_Beyond_Mido")
Adult_LW_Bridge_From_Forest = OOTLocation.new("Adult_LW_Bridge_From_Forest")
Adult_LW_Forest_Exit = OOTLocation.new("Adult_LW_Forest_Exit")
Adult_GC_Woods_Warp = OOTLocation.new("Adult_GC_Woods_Warp")
Adult_LW_Bridge = OOTLocation.new("Adult_LW_Bridge")
Adult_LW_Underwater_Entrance = OOTLocation.new("Adult_LW_Underwater_Entrance")
Adult_Zora_River = OOTLocation.new("Adult_Zora_River")
Adult_LW_Near_Shortcuts_Grotto = OOTLocation.new("Adult_LW_Near_Shortcuts_Grotto")
Adult_Deku_Theater = OOTLocation.new("Adult_Deku_Theater")
Adult_LW_Scrubs_Grotto = OOTLocation.new("Adult_LW_Scrubs_Grotto")

-- Adult_LW_Near_Shortcuts_Grotto = OOTLocation.new("Adult_LW_Near_Shortcuts_Grotto")

--LLR
Child_Lon_Lon_Ranch = OOTLocation.new("Child_Lon_Lon_Ranch")
Child_LLR_Talons_House = OOTLocation.new("Child_LLR_Talons_House")
Child_LLR_Stables = OOTLocation.new("Child_LLR_Stables")
Child_LLR_Tower = OOTLocation.new("Child_LLR_Tower")
Child_LLR_Grotto = OOTLocation.new("Child_LLR_Grotto")

Adult_Lon_Lon_Ranch = OOTLocation.new("Adult_Lon_Lon_Ranch")
Adult_LLR_Talons_House = OOTLocation.new("Adult_LLR_Talons_House")
Adult_LLR_Stables = OOTLocation.new("Adult_LLR_Stables")
Adult_LLR_Tower = OOTLocation.new("Adult_LLR_Tower")
Adult_LLR_Grotto = OOTLocation.new("Adult_LLR_Grotto")

--LH
Child_Lake_Hylia = OOTLocation.new("Child_Lake_Hylia")
Child_LH_Owl_Flight = OOTLocation.new("Child_LH_Owl_Flight")
Child_LH_Lab = OOTLocation.new("Child_LH_Lab")
Child_LH_Fishing_Island = OOTLocation.new("Child_LH_Fishing_Island")
Child_LH_Grotto = OOTLocation.new("Child_LH_Grotto")
Child_Fishing_Hole = OOTLocation.new("Child_Fishing_Hole")

Adult_Lake_Hylia = OOTLocation.new("Adult_Lake_Hylia")
Adult_LH_Owl_Flight = OOTLocation.new("Adult_LH_Owl_Flight")
Adult_LH_Fishing_Island = OOTLocation.new("Adult_LH_Fishing_Island")
Adult_LH_Grotto = OOTLocation.new("Adult_LH_Grotto")
Adult_Fishing_Hole = OOTLocation.new("Adult_Fishing_Hole")
Adult_LH_Lab = OOTLocation.new("Adult_LH_Lab")

--KF
Child_Kokiri_Forest = OOTLocation.new("Child_Kokiri_Forest")
Child_Links_House = OOTLocation.new("Child_Links_House")
Child_Midos_House = OOTLocation.new("Child_Midos_House")
Child_Sarias_House = OOTLocation.new("Child_Sarias_House")
Child_House_Of_Twins = OOTLocation.new("Child_House_Of_Twins")
Child_Know_It_All_House = OOTLocation.new("Child_Know_It_All_House")
Child_Kokiri_Shop = OOTLocation.new("Child_Kokiri_Shop")
Child_KF_Outside_Deku_Tree = OOTLocation.new("Child_KF_Outside_Deku_Tree")
Child_KF_Storms_Grotto = OOTLocation.new("Child_KF_Storms_Grotto")

Adult_Kokiri_Forest = OOTLocation.new("Adult_Kokiri_Forest")
Adult_Links_House = OOTLocation.new("Adult_Links_House")
Adult_Midos_House = OOTLocation.new("Adult_Midos_House")
Adult_Sarias_House = OOTLocation.new("Adult_Sarias_House")
Adult_House_Of_Twins = OOTLocation.new("Adult_House_Of_Twins")
Adult_Know_It_All_House = OOTLocation.new("Adult_Know_It_All_House")
Adult_Kokiri_Shop = OOTLocation.new("Adult_Kokiri_Shop")
Adult_KF_Outside_Deku_Tree = OOTLocation.new("Adult_KF_Outside_Deku_Tree")
Adult_KF_Storms_Grotto = OOTLocation.new("Adult_KF_Storms_Grotto")

--Kak
Child_Kakariko_Village = OOTLocation.new("Child_Kakariko_Village")
Child_Kak_Impas_Ledge = OOTLocation.new("Child_Kak_Impas_Ledge")
Child_Kak_Impas_Rooftop = OOTLocation.new("Child_Kak_Impas_Rooftop")
Child_Kak_Odd_Medicine_Rooftop = OOTLocation.new("Child_Kak_Odd_Medicine_Rooftop")
Child_Kak_Backyard = OOTLocation.new("Child_Kak_Backyard")
Child_Kak_Carpenter_Boss_House = OOTLocation.new("Child_Kak_Carpenter_Boss_House")
Child_Kak_House_of_Skulltula = OOTLocation.new("Child_Kak_House_of_Skulltula")
Child_Kak_Impas_House = OOTLocation.new("Child_Kak_Impas_House")
Child_Kak_Impas_House_Back = OOTLocation.new("Child_Kak_Impas_House_Back")
Child_Kak_Impas_House_Near_Cow = OOTLocation.new("Child_Kak_Impas_House_Near_Cow")
Child_Kak_Windmill = OOTLocation.new("Child_Kak_Windmill")
Child_Kak_Bazaar = OOTLocation.new("Child_Kak_Bazaar")
Child_Kak_Shooting_Gallery = OOTLocation.new("Child_Kak_Shooting_Gallery")
Child_Kak_Potion_Shop_Front = OOTLocation.new("Child_Kak_Potion_Shop_Front")
Child_Kak_Potion_Shop_Back = OOTLocation.new("Child_Kak_Potion_Shop_Back")
Child_Kak_Odd_Medicine_Building = OOTLocation.new("Child_Kak_Odd_Medicine_Building")
Child_Kak_Behind_Gate = OOTLocation.new("Child_Kak_Behind_Gate")
Child_Kak_Redead_Grotto = OOTLocation.new("Child_Kak_Redead_Grotto")
Child_Kak_Open_Grotto = OOTLocation.new("Child_Kak_Open_Grotto")
Child_Kak_Impas_House_Cow = OOTLocation.new("Child_Kak_Impas_House_Cow")

Adult_Kakariko_Village = OOTLocation.new("Adult_Kakariko_Village")
Adult_Kak_Impas_Ledge = OOTLocation.new("Adult_Kak_Impas_Ledge")
Adult_Kak_Impas_Rooftop = OOTLocation.new("Adult_Kak_Impas_Rooftop")
Adult_Kak_Odd_Medicine_Rooftop = OOTLocation.new("Adult_Kak_Odd_Medicine_Rooftop")
Adult_Kak_Backyard = OOTLocation.new("Adult_Kak_Backyard")
Adult_Kak_Carpenter_Boss_House = OOTLocation.new("Adult_Kak_Carpenter_Boss_House")
Adult_Kak_House_of_Skulltula = OOTLocation.new("Adult_Kak_House_of_Skulltula")
Adult_Kak_Impas_House = OOTLocation.new("Adult_Kak_Impas_House")
Adult_Kak_Impas_House_Back = OOTLocation.new("Adult_Kak_Impas_House_Back")
Adult_Kak_Impas_House_Near_Cow = OOTLocation.new("Adult_Kak_Impas_House_Near_Cow")
Adult_Kak_Windmill = OOTLocation.new("Adult_Kak_Windmill")
Adult_Kak_Bazaar = OOTLocation.new("Adult_Kak_Bazaar")
Adult_Kak_Shooting_Gallery = OOTLocation.new("Adult_Kak_Shooting_Gallery")
Adult_Kak_Potion_Shop_Front = OOTLocation.new("Adult_Kak_Potion_Shop_Front")
Adult_Kak_Potion_Shop_Back = OOTLocation.new("Adult_Kak_Potion_Shop_Back")
Adult_Kak_Odd_Medicine_Building = OOTLocation.new("Adult_Kak_Odd_Medicine_Building")
Adult_Kak_Behind_Gate = OOTLocation.new("Adult_Kak_Behind_Gate")
Adult_Kak_Redead_Grotto = OOTLocation.new("Adult_Kak_Redead_Grotto")
Adult_Kak_Open_Grotto = OOTLocation.new("Adult_Kak_Open_Grotto")
Adult_Kak_Impas_House_Cow = OOTLocation.new("Adult_Kak_Impas_House_Cow")

--hideout
Child_Hideout_1_Torch_Jail = OOTLocation.new("Child_Hideout_1_Torch_Jail")
Child_Hideout_2_Torches_Jail = OOTLocation.new("Child_Hideout_2_Torches_Jail")
Child_Hideout_3_Torches_Jail = OOTLocation.new("Child_Hideout_3_Torches_Jail")
Child_Hideout_4_Torches_Jail = OOTLocation.new("Child_Hideout_4_Torches_Jail")
Child_Hideout_Kitchen_Hallway = OOTLocation.new("Child_Hideout_Kitchen_Hallway")
Child_Hideout_Kitchen_Front = OOTLocation.new("Child_Hideout_Kitchen_Front")
Child_Hideout_Kitchen_Rear = OOTLocation.new("Child_Hideout_Kitchen_Rear")
Child_Hideout_Kitchen_Pots = OOTLocation.new("Child_Hideout_Kitchen_Pots")
Child_Hideout_Hall_to_Balcony_Lower = OOTLocation.new("Child_Hideout_Hall_to_Balcony_Lower")
Child_Hideout_Hall_to_Balcony_Upper = OOTLocation.new("Child_Hideout_Hall_to_Balcony_Upper")

Adult_Hideout_1_Torch_Jail = OOTLocation.new("Adult_Hideout_1_Torch_Jail")
Adult_Hideout_2_Torches_Jail = OOTLocation.new("Adult_Hideout_2_Torches_Jail")
Adult_Hideout_3_Torches_Jail = OOTLocation.new("Adult_Hideout_3_Torches_Jail")
Adult_Hideout_4_Torches_Jail = OOTLocation.new("Adult_Hideout_4_Torches_Jail")
Adult_Hideout_Kitchen_Hallway = OOTLocation.new("Adult_Hideout_Kitchen_Hallway")
Adult_Hideout_Kitchen_Front = OOTLocation.new("Adult_Hideout_Kitchen_Front")
Adult_Hideout_Kitchen_Rear = OOTLocation.new("Adult_Hideout_Kitchen_Rear")
Adult_Hideout_Kitchen_Pots = OOTLocation.new("Adult_Hideout_Kitchen_Pots")
Adult_Hideout_Hall_to_Balcony_Lower = OOTLocation.new("Adult_Hideout_Hall_to_Balcony_Lower")
Adult_Hideout_Hall_to_Balcony_Upper = OOTLocation.new("Adult_Hideout_Hall_to_Balcony_Upper")

--HF
Child_Hyrule_Fields = OOTLocation.new("Child_Hyrule_Fields")
Child_HF_Southeast_Grotto = OOTLocation.new("Child_HF_Southeast_Grotto")
Child_HF_Open_Grotto = OOTLocation.new("Child_HF_Open_Grotto")
Child_HF_Inside_Fence_Grotto = OOTLocation.new("Child_HF_Inside_Fence_Grotto")
Child_HF_Cow_Grotto = OOTLocation.new("Child_HF_Cow_Grotto")
Child_HF_Near_Market_Grotto = OOTLocation.new("Child_HF_Near_Market_Grotto")
Child_HF_Fairy_Grotto = OOTLocation.new("Child_HF_Fairy_Grotto")
Child_HF_Near_Kak_Grotto = OOTLocation.new("Child_HF_Near_Kak_Grotto")
Child_HF_Tektite_Grotto = OOTLocation.new("Child_HF_Tektite_Grotto")

Adult_Hyrule_Fields = OOTLocation.new("Adult_Hyrule_Fields")
Adult_HF_Southeast_Grotto = OOTLocation.new("Adult_HF_Southeast_Grotto")
Adult_HF_Open_Grotto = OOTLocation.new("Adult_HF_Open_Grotto")
Adult_HF_Inside_Fence_Grotto = OOTLocation.new("Adult_HF_Inside_Fence_Grotto")
Adult_HF_Cow_Grotto = OOTLocation.new("Adult_HF_Cow_Grotto")
Adult_HF_Near_Market_Grotto = OOTLocation.new("Adult_HF_Near_Market_Grotto")
Adult_HF_Fairy_Grotto = OOTLocation.new("Adult_HF_Fairy_Grotto")
Adult_HF_Near_Kak_Grotto = OOTLocation.new("Adult_HF_Near_Kak_Grotto")
Adult_HF_Tektite_Grotto = OOTLocation.new("Adult_HF_Tektite_Grotto")

--HC
Child_Castle_Grounds = OOTLocation.new("Child_Castle_Grounds")
Child_Hyrule_Castle_Grounds = OOTLocation.new("Child_Hyrule_Castle_Grounds")
Child_HC_Garden = OOTLocation.new("Child_HC_Garden")
Child_HC_Garden_Locations = OOTLocation.new("Child_HC_Garden_Locations")
Child_HC_Great_Fairy_Fountain = OOTLocation.new("Child_HC_Great_Fairy_Fountain")
-- Child_Castle_Grounds_From_Ganons_Castle = OOTLocation.new("Child_Castle_Grounds_From_Ganons_Castle")
-- Child_Ganons_Castle_Grounds = OOTLocation.new("Child_Ganons_Castle_Grounds")
-- Child_OGC_Great_Fairy_Fountain = OOTLocation.new("Child_OGC_Great_Fairy_Fountain")
Child_HC_Storms_Grotto = OOTLocation.new("Child_HC_Storms_Grotto")

Adult_Castle_Grounds = OOTLocation.new("Adult_Castle_Grounds")
Adult_Hyrule_Castle_Grounds = OOTLocation.new("Adult_Hyrule_Castle_Grounds")
Adult_HC_Garden = OOTLocation.new("Adult_HC_Garden")
Adult_HC_Garden_Locations = OOTLocation.new("Adult_HC_Garden_Locations")
Adult_HC_Great_Fairy_Fountain = OOTLocation.new("Adult_HC_Great_Fairy_Fountain")
-- Adult_Castle_Grounds_From_Ganons_Castle = OOTLocation.new("Adult_Castle_Grounds_From_Ganons_Castle")
-- Adult_Ganons_Castle_Grounds = OOTLocation.new("Adult_Ganons_Castle_Grounds")
-- Adult_OGC_Great_Fairy_Fountain = OOTLocation.new("Adult_OGC_Great_Fairy_Fountain")
Adult_HC_Storms_Grotto = OOTLocation.new("Adult_HC_Storms_Grotto")

--GV
Child_Gerudo_Valley = OOTLocation.new("Child_Gerudo_Valley")
Child_GV_Upper_Stream = OOTLocation.new("Child_GV_Upper_Stream")
Child_GV_Crate_Ledge = OOTLocation.new("Child_GV_Crate_Ledge")
Child_GV_Grotto_Ledge = OOTLocation.new("Child_Grotto_Ledge")
Child_GV_Lower_Stream = OOTLocation.new("Child_GV_Lower_Stream")
Child_GV_Fortress_Side = OOTLocation.new("Child_GV_Fortress_Side")
Child_GV_Octorok_Grotto = OOTLocation.new("Child_GV_Octorok_Grotto")
Child_GV_Storms_Grotto = OOTLocation.new("Child_GV_Storms_Grotto")
Child_GV_Carpenter_Tent = OOTLocation.new("Child_GV_Carpenter_Tent")

Adult_Gerudo_Valley = OOTLocation.new("Adult_Gerudo_Valley")
Adult_GV_Upper_Stream = OOTLocation.new("Adult_GV_Upper_Stream")
Adult_GV_Crate_Ledge = OOTLocation.new("Adult_GV_Crate_Ledge")
Adult_GV_Grotto_Ledge = OOTLocation.new("Adult_GV_Grotto_Ledge")
Adult_GV_Fortress_Side = OOTLocation.new("Adult_GV_Fortress_Side")
Adult_GV_Lower_Stream = OOTLocation.new("Adult_GV_Lower_Stream")
Adult_GV_Octorok_Grotto = OOTLocation.new("Adult_GV_Octorok_Grotto")
Adult_GV_Carpenter_Tent = OOTLocation.new("Adult_GV_Carpenter_Tent")
Adult_GV_Storms_Grotto = OOTLocation.new("Adult_GV_Storms_Grotto")

-- Graveyard
Child_Graveyard = OOTLocation.new("Child_Graveyard")
Child_Graveyard_Shield_Grave = OOTLocation.new("Child_Graveyard_Shield_Grave")
Child_Graveyard_Heart_Piece_Grave = OOTLocation.new("Child_Graveyard_Heart_Piece_Grave")
Child_Graveyard_Royal_Familys_Tomb = OOTLocation.new("Child_Graveyard_Royal_Familys_Tomb")
Child_Graveyard_Dampes_Grave = OOTLocation.new("Child_Graveyard_Dampes_Grave")
Child_Graveyard_Dampes_House = OOTLocation.new("Child_Graveyard_Dampes_House")
Child_Graveyard_Warp_Pad_Region = OOTLocation.new("Child_Graveyard_Warp_Pad_Region")

Adult_Graveyard = OOTLocation.new("Adult_Graveyard")
Adult_Graveyard_Shield_Grave = OOTLocation.new("Adult_Graveyard_Shield_Grave")
Adult_Graveyard_Heart_Piece_Grave = OOTLocation.new("Adult_Graveyard_Heart_Piece_Grave")
Adult_Graveyard_Royal_Familys_Tomb = OOTLocation.new("Adult_Graveyard_Royal_Familys_Tomb")
Adult_Graveyard_Dampes_Grave = OOTLocation.new("Adult_Graveyard_Dampes_Grave")
Adult_Graveyard_Dampes_House = OOTLocation.new("Adult_Graveyard_Dampes_House")
Adult_Graveyard_Warp_Pad_Region = OOTLocation.new("Adult_Graveyard_Warp_Pad_Region")

-- GF
Child_Gerudo_Fortress = OOTLocation.new("Child_Gerudo_Fortress")
Child_GF_Entrances_Behind_Crates = OOTLocation.new("Child_GF_Entrances_Behind_Crates")
Child_GF_Roof_Entrance_Cluster = OOTLocation.new("Child_GF_Roof_Entrance_Cluster")
Child_GF_Kitchen_Roof_Access = OOTLocation.new("Child_GF_Kitchen_Roof_Access")
Child_GF_Hall_to_Balcony_Entrance = OOTLocation.new("Child_GF_Hall_to_Balcony_Entrance")
Child_GF_Outside_Gate = OOTLocation.new("Child_GF_Outside_Gate")
Child_GF_Storms_Grotto = OOTLocation.new("Child_GF_Storms_Grotto")
Child_GF_3_Torches_Jail_Exterior = OOTLocation.new("Child_GF_3_Torches_Jail_Exterior")
Child_GF_Chest_Roof = OOTLocation.new("Child_GF_Chest_Roof")
Child_GF_Roof_Gold_Skulltula = OOTLocation.new("Child_GF_Roof_Gold_Skulltula")
Child_GF_Hall_to_Balcony_Entrance = OOTLocation.new("Child_GF_Hall_to_Balcony_Entrance")
Child_GF_Balcony = OOTLocation.new("Child_GF_Balcony")
-- Child_Wasteland_Near_Fortress = OOTLocation.new("Child_Wasteland_Near_Fortress")


Adult_Gerudo_Fortress = OOTLocation.new("Adult_Gerudo_Fortress")
Adult_GF_Entrances_Behind_Crates = OOTLocation.new("Adult_GF_Entrances_Behind_Crates")
Adult_GF_Roof_Entrance_Cluster = OOTLocation.new("Adult_GF_Roof_Entrance_Cluster")
Adult_GF_Kitchen_Roof_Access = OOTLocation.new("Adult_GF_Kitchen_Roof_Access")
Adult_GF_Hall_to_Balcony_Entrance = OOTLocation.new("Adult_GF_Hall_to_Balcony_Entrance")
Adult_GF_Outside_Gate = OOTLocation.new("Adult_GF_Outside_Gate")
Adult_GF_Storms_Grotto = OOTLocation.new("Adult_GF_Storms_Grotto")
Adult_GF_3_Torches_Jail_Exterior = OOTLocation.new("Adult_GF_3_Torches_Jail_Exterior")
Adult_GF_Chest_Roof = OOTLocation.new("Adult_GF_Chest_Roof")
Adult_GF_Roof_Gold_Skulltula = OOTLocation.new("Adult_GF_Roof_Gold_Skulltula")
Adult_GF_Hall_to_Balcony_Entrance = OOTLocation.new("Adult_GF_Hall_to_Balcony_Entrance")
Adult_GF_Balcony = OOTLocation.new("Adult_GF_Balcony")
-- Adult_Wasteland_Near_Fortress = OOTLocation.new("Adult_Wasteland_Near_Fortress")

-- GC
Child_Goron_City = OOTLocation.new("Child_Goron_City")
Child_GC_Woods_Warp = OOTLocation.new("Child_GC_Woods_Warp")
Child_GC_Darunias_Chamber = OOTLocation.new("Child_GC_Darunias_Chamber")
Child_GC_Grotto_Platform = OOTLocation.new("Child_GC_Grotto_Platform")
Child_GC_Spinning_Pot = OOTLocation.new("Child_GC_Spinning_Pot")
Child_GC_Shop = OOTLocation.new("Child_GC_Shop")
Child_GC_Grotto = OOTLocation.new("Child_GC_Grotto")

Adult_Goron_City = OOTLocation.new("Adult_Goron_City")
Adult_GC_Woods_Warp = OOTLocation.new("Adult_GC_Woods_Warp")
Adult_GC_Darunias_Chamber = OOTLocation.new("Adult_GC_Darunias_Chamber")
Adult_GC_Grotto_Platform = OOTLocation.new("Adult_GC_Grotto_Platform")
Adult_GC_Spinning_Pot = OOTLocation.new("Adult_GC_Spinning_Pot")
Adult_GC_Shop = OOTLocation.new("Adult_GC_Shop")
Adult_GC_Grotto = OOTLocation.new("Adult_GC_Grotto")

--  DMT
Child_Death_Mountain = OOTLocation.new("Child_Death_Mountain")
Child_Death_Mountain_Summit = OOTLocation.new("Child_Death_Mountain_Summit")
Child_DMT_Owl_Flight = OOTLocation.new("Child_DMT_Owl_Flight")
Child_DMT_Great_Fairy_Fountain = OOTLocation.new("Child_DMT_Great_Fairy_Fountain")
Child_DMT_Cow_Grotto = OOTLocation.new("Child_DMT_Cow_Grotto")
Child_DMT_Storms_Grotto = OOTLocation.new("Child_DMT_Storms_Grotto")

Adult_Death_Mountain = OOTLocation.new("Adult_Death_Mountain")
Adult_Death_Mountain_Summit = OOTLocation.new("Adult_Death_Mountain_Summit")
Adult_DMT_Owl_Flight = OOTLocation.new("Adult_DMT_Owl_Flight")
Adult_DMT_Great_Fairy_Fountain = OOTLocation.new("Adult_DMT_Great_Fairy_Fountain")
Adult_DMT_Cow_Grotto = OOTLocation.new("Adult_DMT_Cow_Grotto")
Adult_DMT_Storms_Grotto = OOTLocation.new("Adult_DMT_Storms_Grotto")

--DMC
Child_DMC_Upper_Nearby = OOTLocation.new("Child_DMC_Upper_Nearby")
Child_DMC_Upper_Local = OOTLocation.new("Child_DMC_Upper_Local")
Child_DMC_Pierre_Platform = OOTLocation.new("Child_DMC_Pierre_Platform")
Child_DMC_Ladder_Area_Nearby = OOTLocation.new("Child_DMC_Ladder_Area_Nearby")
Child_DMC_Lower_Nearby = OOTLocation.new("Child_DMC_Lower_Nearby")
Child_DMC_Lower_Local = OOTLocation.new("Child_DMC_Lower_Local")
Child_DMC_Central_Nearby = OOTLocation.new("Child_DMC_Central_Nearby")
Child_DMC_Central_Local = OOTLocation.new("Child_DMC_Central_Local")
Child_DMC_Fire_Temple_Entrance = OOTLocation.new("Child_DMC_Fire_Temple_Entrance")
Child_DMC_Great_Fairy_Fountain = OOTLocation.new("Child_DMC_Great_Fairy_Fountain")
Child_DMC_Upper_Grotto = OOTLocation.new("Child_DMC_Upper_Grotto")
Child_DMC_Hammer_Grotto = OOTLocation.new("Child_DMC_Hammer_Grotto")

Adult_DMC_Upper_Nearby = OOTLocation.new("Adult_DMC_Upper_Nearby")
Adult_DMC_Upper_Local = OOTLocation.new("Adult_DMC_Upper_Local")
Adult_DMC_Pierre_Platform = OOTLocation.new("Adult_DMC_Pierre_Platform")
Adult_DMC_Ladder_Area_Nearby = OOTLocation.new("Adult_DMC_Ladder_Area_Nearby")
Adult_DMC_Lower_Nearby = OOTLocation.new("Adult_DMC_Lower_Nearby")
Adult_DMC_Lower_Local = OOTLocation.new("Adult_DMC_Lower_Local")
Adult_DMC_Central_Nearby = OOTLocation.new("Adult_DMC_Central_Nearby")
Adult_DMC_Central_Local = OOTLocation.new("Adult_DMC_Central_Local")
Adult_DMC_Fire_Temple_Entrance = OOTLocation.new("Adult_DMC_Fire_Temple_Entrance")
Adult_DMC_Great_Fairy_Fountain = OOTLocation.new("Adult_DMC_Great_Fairy_Fountain")
Adult_DMC_Upper_Grotto = OOTLocation.new("Adult_DMC_Upper_Grotto")
Adult_DMC_Hammer_Grotto = OOTLocation.new("Adult_DMC_Hammer_Grotto")

-- BotW

Child_Bottom_of_the_Well = OOTLocation.new("Child_Bottom_of_the_Well")
Child_Bottom_of_the_Well_Main_Area = OOTLocation.new("Child_Bottom_of_the_Well_Main_Area")
Child_Bottom_of_the_Well_Behind_Fake_Walls = OOTLocation.new("Child_Bottom_of_the_Well_Behind_Fake_Walls")
Child_Bottom_of_the_Well_Behind_Locked_Doors = OOTLocation.new("Child_Bottom_of_the_Well_Behind_Locked_Doors")
Child_Bottom_of_the_Well_Perimeter = OOTLocation.new("Child_Bottom_of_the_Well_Perimeter")
Child_Bottom_of_the_Well_Middle = OOTLocation.new("Child_Bottom_of_the_Well_Middle")

Adult_Bottom_of_the_Well = OOTLocation.new("Adult_Bottom_of_the_Well")
Adult_Bottom_of_the_Well_Main_Area = OOTLocation.new("Adult_Bottom_of_the_Well_Main_Area")
Adult_Bottom_of_the_Well_Behind_Fake_Walls = OOTLocation.new("Adult_Bottom_of_the_Well_Behind_Fake_Walls")
Adult_Bottom_of_the_Well_Behind_Locked_Doors = OOTLocation.new("Adult_Bottom_of_the_Well_Behind_Locked_Doors")
Adult_Bottom_of_the_Well_Perimeter = OOTLocation.new("Adult_Bottom_of_the_Well_Perimeter")
Adult_Bottom_of_the_Well_Middle = OOTLocation.new("Adult_Bottom_of_the_Well_Middle")

-- Deku Tree

Child_Deku_Tree_Lobby = OOTLocation.new("Child_Deku_Tree_Lobby")
Child_Deku_Tree_Slingshot_Room = OOTLocation.new("Child_Deku_Tree_Slingshot_Room")
Child_Deku_Tree_Basement = OOTLocation.new("Child_Deku_Tree_Basement")
Child_Deku_Tree_Basement_Back_Room = OOTLocation.new("Child_Deku_Tree_Basement_Back_Room")
Child_Deku_Tree_Basement_Ledge = OOTLocation.new("Child_Deku_Tree_Basement_Ledge")
Child_Deku_Tree_Before_Boss = OOTLocation.new("Child_Deku_Tree_Before_Boss")
Child_Deku_Tree_Near_Compass_Room = OOTLocation.new("Child_Deku_Tree_Near_Compass_Room")
Child_Deku_Tree_Compass_Room = OOTLocation.new("Child_Deku_Tree_Compass_Room")
Child_Deku_Tree_Basement_Water_Room_Front = OOTLocation.new("Child_Deku_Tree_Basement_Water_Room_Front")
Child_Deku_Tree_Basement_Water_Room_Back = OOTLocation.new("Child_Deku_Tree_Basement_Water_Room_Back")

Adult_Deku_Tree_Lobby = OOTLocation.new("Adult_Deku_Tree_Lobby")
Adult_Deku_Tree_Slingshot_Room = OOTLocation.new("Adult_Deku_Tree_Slingshot_Room")
Adult_Deku_Tree_Basement = OOTLocation.new("Adult_Deku_Tree_Basement")
Adult_Deku_Tree_Basement_Back_Room = OOTLocation.new("Adult_Deku_Tree_Basement_Back_Room")
Adult_Deku_Tree_Basement_Ledge = OOTLocation.new("Adult_Deku_Tree_Basement_Ledge")
Adult_Deku_Tree_Before_Boss = OOTLocation.new("Adult_Deku_Tree_Before_Boss")
Adult_Deku_Tree_Near_Compass_Room = OOTLocation.new("Adult_Deku_Tree_Near_Compass_Room")
Adult_Deku_Tree_Compass_Room = OOTLocation.new("Adult_Deku_Tree_Compass_Room")
Adult_Deku_Tree_Basement_Water_Room_Front = OOTLocation.new("Adult_Deku_Tree_Basement_Water_Room_Front")
Adult_Deku_Tree_Basement_Water_Room_Back = OOTLocation.new("Adult_Deku_Tree_Basement_Water_Room_Back")
-- Dodongdos Cavern

Child_Dodongos_Cavern_Beginning = OOTLocation.new("Child_Dodongos_Cavern_Beginning")
Child_Dodongos_Cavern_Lobby = OOTLocation.new("Child_Dodongos_Cavern_Lobby")
Child_Dodongos_Cavern_Lower_Right_Side = OOTLocation.new("Child_Dodongos_Cavern_Lower_Right_Side")
Child_Dodongos_Cavern_Torch_Room = OOTLocation.new("Child_Dodongos_Cavern_Torch_Room")
Child_Dodongos_Cavern_Staircase_Room = OOTLocation.new("Child_Dodongos_Cavern_Staircase_Room")
Child_Dodongos_Cavern_Climb = OOTLocation.new("Child_Dodongos_Cavern_Climb")
Child_Dodongos_Cavern_Before_Upper_Lizalfos = OOTLocation.new("Child_Dodongos_Cavern_Before_Upper_Lizalfos")
Child_Dodongos_Cavern_Upper_Lizalfos = OOTLocation.new("Child_Dodongos_Cavern_Upper_Lizalfos")
Child_Dodongos_Cavern_Far_Bridge = OOTLocation.new("Child_Dodongos_Cavern_Far_Bridge")
Child_Dodongos_Cavern_Before_Boss = OOTLocation.new("Child_Dodongos_Cavern_Before_Boss")

Adult_Dodongos_Cavern_Beginning = OOTLocation.new("Adult_Dodongos_Cavern_Beginning")
Adult_Dodongos_Cavern_Lobby = OOTLocation.new("Adult_Dodongos_Cavern_Lobby")
Adult_Dodongos_Cavern_Lower_Right_Side = OOTLocation.new("Adult_Dodongos_Cavern_Lower_Right_Side")
Adult_Dodongos_Cavern_Torch_Room = OOTLocation.new("Adult_Dodongos_Cavern_Torch_Room")
Adult_Dodongos_Cavern_Staircase_Room = OOTLocation.new("Adult_Dodongos_Cavern_Staircase_Room")
Adult_Dodongos_Cavern_Climb = OOTLocation.new("Adult_Dodongos_Cavern_Climb")
Adult_Dodongos_Cavern_Before_Upper_Lizalfos = OOTLocation.new("Adult_Dodongos_Cavern_Before_Upper_Lizalfos")
Adult_Dodongos_Cavern_Upper_Lizalfos = OOTLocation.new("Adult_Dodongos_Cavern_Upper_Lizalfos")
Adult_Dodongos_Cavern_Far_Bridge = OOTLocation.new("Adult_Dodongos_Cavern_Far_Bridge")
Adult_Dodongos_Cavern_Before_Boss = OOTLocation.new("Adult_Dodongos_Cavern_Before_Boss")

--FiT

Child_Fire_Temple_Lower = OOTLocation.new("Child_Fire_Temple_Lower")
Child_Fire_Temple_Lower_Locked_Door = OOTLocation.new("Child_Fire_Temple_Lower_Locked_Door")
Child_Fire_Temple_Big_Lava_Room = OOTLocation.new("Child_Fire_Temple_Big_Lava_Room")
Child_Fire_Temple_Elevator_Room = OOTLocation.new("Child_Fire_Temple_Elevator_Room")
Child_Fire_Temple_Boulder_Maze_Lower = OOTLocation.new("Child_Fire_Temple_Boulder_Maze_Lower")
Child_Fire_Temple_Narrow_Path_Room = OOTLocation.new("Child_Fire_Temple_Narrow_Path_Room")
Child_Fire_Temple_Boulder_Maze_Upper = OOTLocation.new("Child_Fire_Temple_Boulder_Maze_Upper")
Child_Fire_Temple_Flame_Maze = OOTLocation.new("Child_Fire_Temple_Flame_Maze")
Child_Fire_Temple_Upper = OOTLocation.new("Child_Fire_Temple_Upper")

Adult_Fire_Temple_Lower = OOTLocation.new("Adult_Fire_Temple_Lower")
Adult_Fire_Temple_Lower_Locked_Door = OOTLocation.new("Adult_Fire_Temple_Lower_Locked_Door")
Adult_Fire_Temple_Big_Lava_Room = OOTLocation.new("Adult_Fire_Temple_Big_Lava_Room")
Adult_Fire_Temple_Elevator_Room = OOTLocation.new("Adult_Fire_Temple_Elevator_Room")
Adult_Fire_Temple_Boulder_Maze_Lower = OOTLocation.new("Adult_Fire_Temple_Boulder_Maze_Lower")
Adult_Fire_Temple_Narrow_Path_Room = OOTLocation.new("Adult_Fire_Temple_Narrow_Path_Room")
Adult_Fire_Temple_Boulder_Maze_Upper = OOTLocation.new("Adult_Fire_Temple_Boulder_Maze_Upper")
Adult_Fire_Temple_Flame_Maze = OOTLocation.new("Adult_Fire_Temple_Flame_Maze")
Adult_Fire_Temple_Upper = OOTLocation.new("Adult_Fire_Temple_Upper")

--FoT

Child_Forest_Temple_Lobby = OOTLocation.new("Child_Forest_Temple_Lobby")
Child_Forest_Temple_Central_Area = OOTLocation.new("Child_Forest_Temple_Central_Area")
Child_Forest_Temple_NW_Outdoors = OOTLocation.new("Child_Forest_Temple_NW_Outdoors")
Child_Forest_Temple_Outdoors_High_Balconies = OOTLocation.new("Child_Forest_Temple_Outdoors_High_Balconies")
Child_Forest_Temple_NE_Outdoors = OOTLocation.new("Child_Forest_Temple_NE_Outdoors")
Child_Forest_Temple_Block_Push_Room = OOTLocation.new("Child_Forest_Temple_Block_Push_Room")
Child_Forest_Temple_Straightened_Hall = OOTLocation.new("Child_Forest_Temple_Straightened_Hall")
Child_Forest_Temple_Outside_Upper_Ledge = OOTLocation.new("Child_Forest_Temple_Outside_Upper_Ledge")
Child_Forest_Temple_Bow_Region = OOTLocation.new("Child_Forest_Temple_Bow_Region")
Child_Forest_Temple_Frozen_Eye_Switch_Room = OOTLocation.new("Child_Forest_Temple_Frozen_Eye_Switch_Room")
Child_Forest_Temple_Falling_Room = OOTLocation.new("Child_Forest_Temple_Falling_Room")
Child_Forest_Temple_Before_Boss = OOTLocation.new("Child_Forest_Temple_Before_Boss")

Adult_Forest_Temple_Lobby = OOTLocation.new("Adult_Forest_Temple_Lobby")
Adult_Forest_Temple_Central_Area = OOTLocation.new("Adult_Forest_Temple_Central_Area")
Adult_Forest_Temple_NW_Outdoors = OOTLocation.new("Adult_Forest_Temple_NW_Outdoors")
Adult_Forest_Temple_Outdoors_High_Balconies = OOTLocation.new("Adult_Forest_Temple_Outdoors_High_Balconies")
Adult_Forest_Temple_NE_Outdoors = OOTLocation.new("Adult_Forest_Temple_NE_Outdoors")
Adult_Forest_Temple_Block_Push_Room = OOTLocation.new("Adult_Forest_Temple_Block_Push_Room")
Adult_Forest_Temple_Straightened_Hall = OOTLocation.new("Adult_Forest_Temple_Straightened_Hall")
Adult_Forest_Temple_Outside_Upper_Ledge = OOTLocation.new("Adult_Forest_Temple_Outside_Upper_Ledge")
Adult_Forest_Temple_Bow_Region = OOTLocation.new("Adult_Forest_Temple_Bow_Region")
Adult_Forest_Temple_Frozen_Eye_Switch_Room = OOTLocation.new("Adult_Forest_Temple_Frozen_Eye_Switch_Room")
Adult_Forest_Temple_Falling_Room = OOTLocation.new("Adult_Forest_Temple_Falling_Room")
Adult_Forest_Temple_Before_Boss = OOTLocation.new("Adult_Forest_Temple_Before_Boss")

-- Ganons Castle

Child_Castle_Grounds_From_Ganons_Castle = OOTLocation.new("Child_Castle_Grounds_From_Ganons_Castle")
Child_Ganons_Castle_Grounds = OOTLocation.new("Child_Ganons_Castle_Grounds")
Child_OGC_Great_Fairy_Fountain = OOTLocation.new("Child_OGC_Great_Fairy_Fountain")

Adult_Castle_Grounds_From_Ganons_Castle = OOTLocation.new("Adult_Castle_Grounds_From_Ganons_Castle")
Adult_Ganons_Castle_Grounds = OOTLocation.new("Adult_Ganons_Castle_Grounds")
Adult_OGC_Great_Fairy_Fountain = OOTLocation.new("Adult_OGC_Great_Fairy_Fountain")

-- Ganos Tower

Child_Ganons_Castle_Lobby = OOTLocation.new("Child_Ganons_Castle_Lobby")
Child_Ganons_Castle_Forest_Trial = OOTLocation.new("Child_Ganons_Castle_Forest_Trial")
Child_Ganons_Castle_Forest_Trial_Ending = OOTLocation.new("Child_Ganons_Castle_Forest_Trial_Ending")
Child_Ganons_Castle_Water_Trial = OOTLocation.new("Child_Ganons_Castle_Water_Trial")
Child_Ganons_Castle_Water_Trial_Ending = OOTLocation.new("Child_Ganons_Castle_Water_Trial_Ending")
Child_Ganons_Castle_Shadow_Trial = OOTLocation.new("Child_Ganons_Castle_Shadow_Trial")
Child_Ganons_Castle_Shadow_Trial_First_Gap = OOTLocation.new("Child_Ganons_Castle_Shadow_Trial_First_Gap")
Child_Ganons_Castle_Shadow_Trial_Second_Gap = OOTLocation.new("Child_Ganons_Castle_Shadow_Trial_Second_Gap")
Child_Ganons_Castle_Shadow_Trial_Ending = OOTLocation.new("Child_Ganons_Castle_Shadow_Trial_Ending")
Child_Ganons_Castle_Fire_Trial = OOTLocation.new("Child_Ganons_Castle_Fire_Trial")
Child_Ganons_Castle_Fire_Trial_Ending = OOTLocation.new("Child_Ganons_Castle_Fire_Trial_Ending")
Child_Ganons_Castle_Light_Trial = OOTLocation.new("Child_Ganons_Castle_Light_Trial")
Child_Ganons_Castle_Light_Trial_Boulder_Room = OOTLocation.new("Child_Ganons_Castle_Light_Trial_Boulder_Room")
Child_Ganons_Castle_Light_Trial_Ending = OOTLocation.new("Child_Ganons_Castle_Light_Trial_Ending")
Child_Ganons_Castle_Spirit_Trial = OOTLocation.new("Child_Ganons_Castle_Spirit_Trial")
Child_Ganons_Castle_Spirit_Trial_Second_Room_Front = OOTLocation.new("Child_Ganons_Castle_Spirit_Trial_Second_Room_Front")
Child_Ganons_Castle_Spirit_Trial_Second_Room_Back = OOTLocation.new("Child_Ganons_Castle_Spirit_Trial_Second_Room_Back")
Child_Ganons_Castle_Spirit_Trial_Ending = OOTLocation.new("Child_Ganons_Castle_Spirit_Trial_Ending")
Child_Ganons_Castle_Deku_Scrubs = OOTLocation.new("Child_Ganons_Castle_Deku_Scrubs")

Adult_Ganons_Castle_Lobby = OOTLocation.new("Adult_Ganons_Castle_Lobby")
Adult_Ganons_Castle_Forest_Trial = OOTLocation.new("Adult_Ganons_Castle_Forest_Trial")
Adult_Ganons_Castle_Forest_Trial_Ending = OOTLocation.new("Adult_Ganons_Castle_Forest_Trial_Ending")
Adult_Ganons_Castle_Water_Trial = OOTLocation.new("Adult_Ganons_Castle_Water_Trial")
Adult_Ganons_Castle_Water_Trial_Ending = OOTLocation.new("Adult_Ganons_Castle_Water_Trial_Ending")
Adult_Ganons_Castle_Shadow_Trial = OOTLocation.new("Adult_Ganons_Castle_Shadow_Trial")
Adult_Ganons_Castle_Shadow_Trial_First_Gap = OOTLocation.new("Adult_Ganons_Castle_Shadow_Trial_First_Gap")
Adult_Ganons_Castle_Shadow_Trial_Second_Gap = OOTLocation.new("Adult_Ganons_Castle_Shadow_Trial_Second_Gap")
Adult_Ganons_Castle_Shadow_Trial_Ending = OOTLocation.new("Adult_Ganons_Castle_Shadow_Trial_Ending")
Adult_Ganons_Castle_Fire_Trial = OOTLocation.new("Adult_Ganons_Castle_Fire_Trial")
Adult_Ganons_Castle_Fire_Trial_Ending = OOTLocation.new("Adult_Ganons_Castle_Fire_Trial_Ending")
Adult_Ganons_Castle_Light_Trial = OOTLocation.new("Adult_Ganons_Castle_Light_Trial")
Adult_Ganons_Castle_Light_Trial_Boulder_Room = OOTLocation.new("Adult_Ganons_Castle_Light_Trial_Boulder_Room")
Adult_Ganons_Castle_Light_Trial_Ending = OOTLocation.new("Adult_Ganons_Castle_Light_Trial_Ending")
Adult_Ganons_Castle_Spirit_Trial = OOTLocation.new("Adult_Ganons_Castle_Spirit_Trial")
Adult_Ganons_Castle_Spirit_Trial_Second_Room_Front = OOTLocation.new("Adult_Ganons_Castle_Spirit_Trial_Second_Room_Front")
Adult_Ganons_Castle_Spirit_Trial_Second_Room_Back = OOTLocation.new("Adult_Ganons_Castle_Spirit_Trial_Second_Room_Back")
Adult_Ganons_Castle_Spirit_Trial_Ending = OOTLocation.new("Adult_Ganons_Castle_Spirit_Trial_Ending")
Adult_Ganons_Castle_Deku_Scrubs = OOTLocation.new("Adult_Ganons_Castle_Deku_Scrubs")

-- GTG

Child_Gerudo_Training_Ground_Lobby = OOTLocation.new("Child_Gerudo_Training_Ground_Lobby")
Child_Gerudo_Training_Ground_Lava_Room = OOTLocation.new("Child_Gerudo_Training_Ground_Lava_Room")
Child_Gerudo_Training_Ground_Central_Maze_Right = OOTLocation.new("Child_Gerudo_Training_Ground_Central_Maze_Right")
Child_Gerudo_Training_Ground_Heavy_Block_Room = OOTLocation.new("Child_Gerudo_Training_Ground_Heavy_Block_Room")
Child_Gerudo_Training_Ground_Eye_Statue_Upper = OOTLocation.new("Child_Gerudo_Training_Ground_Eye_Statue_Upper")
Child_Gerudo_Training_Ground_Like_Like_Room = OOTLocation.new("Child_Gerudo_Training_Ground_Like_Like_Room")
Child_Gerudo_Training_Ground_Eye_Statue_Lower = OOTLocation.new("Child_Gerudo_Training_Ground_Eye_Statue_Lower")
Child_Gerudo_Training_Ground_Hammer_Room = OOTLocation.new("Child_Gerudo_Training_Ground_Hammer_Room")

Adult_Gerudo_Training_Ground_Lobby = OOTLocation.new("Adult_Gerudo_Training_Ground_Lobby")
Adult_Gerudo_Training_Ground_Lava_Room = OOTLocation.new("Adult_Gerudo_Training_Ground_Lava_Room")
Adult_Gerudo_Training_Ground_Central_Maze_Right = OOTLocation.new("Adult_Gerudo_Training_Ground_Central_Maze_Right")
Adult_Gerudo_Training_Ground_Heavy_Block_Room = OOTLocation.new("Adult_Gerudo_Training_Ground_Heavy_Block_Room")
Adult_Gerudo_Training_Ground_Eye_Statue_Upper = OOTLocation.new("Adult_Gerudo_Training_Ground_Eye_Statue_Upper")
Adult_Gerudo_Training_Ground_Like_Like_Room = OOTLocation.new("Adult_Gerudo_Training_Ground_Like_Like_Room")
Adult_Gerudo_Training_Ground_Eye_Statue_Lower = OOTLocation.new("Adult_Gerudo_Training_Ground_Eye_Statue_Lower")
Adult_Gerudo_Training_Ground_Hammer_Room = OOTLocation.new("Adult_Gerudo_Training_Ground_Hammer_Room")

--Ice cavern

Child_Ice_Cavern_Beginning = OOTLocation.new("Child_Ice_Cavern_Beginning")
Child_Ice_Cavern_Spinning_Blades = OOTLocation.new("Child_Ice_Cavern_Spinning_Blades")
Child_Ice_Cavern_Map_Room = OOTLocation.new("Child_Ice_Cavern_Map_Room")
Child_Ice_Cavern_Behind_Ice_Walls = OOTLocation.new("Child_Ice_Cavern_Behind_Ice_Walls")

Adult_Ice_Cavern_Beginning = OOTLocation.new("Adult_Ice_Cavern_Beginning")
Adult_Ice_Cavern_Spinning_Blades = OOTLocation.new("Adult_Ice_Cavern_Spinning_Blades")
Adult_Ice_Cavern_Map_Room = OOTLocation.new("Adult_Ice_Cavern_Map_Room")
Adult_Ice_Cavern_Behind_Ice_Walls = OOTLocation.new("Adult_Ice_Cavern_Behind_Ice_Walls")

-- JJB

Child_Jabu_Jabus_Belly_Beginning = OOTLocation.new("Child_Jabu_Jabus_Belly_Beginning")
Child_Jabu_Jabus_Belly_Main = OOTLocation.new("Child_Jabu_Jabus_Belly_Main")
Child_Jabu_Jabus_Belly_Depths = OOTLocation.new("Child_Jabu_Jabus_Belly_Depths")
Child_Jabu_Jabus_Belly_Past_Big_Octo = OOTLocation.new("Child_Jabu_Jabus_Belly_Past_Big_Octo")
Child_Jabu_Jabus_Belly_Before_Boss = OOTLocation.new("Child_Jabu_Jabus_Belly_Before_Boss")

Adult_Jabu_Jabus_Belly_Beginning = OOTLocation.new("Adult_Jabu_Jabus_Belly_Beginning")
Adult_Jabu_Jabus_Belly_Main = OOTLocation.new("Adult_Jabu_Jabus_Belly_Main")
Adult_Jabu_Jabus_Belly_Depths = OOTLocation.new("Adult_Jabu_Jabus_Belly_Depths")
Adult_Jabu_Jabus_Belly_Past_Big_Octo = OOTLocation.new("Adult_Jabu_Jabus_Belly_Past_Big_Octo")
Adult_Jabu_Jabus_Belly_Before_Boss = OOTLocation.new("Adult_Jabu_Jabus_Belly_Before_Boss")

-- ShadowTemple

Child_Shadow_Temple_Entryway = OOTLocation.new("Child_Shadow_Temple_Entryway")
Child_Shadow_Temple_Beginning = OOTLocation.new("Child_Shadow_Temple_Beginning")
Child_Shadow_Temple_First_Beamos = OOTLocation.new("Child_Shadow_Temple_First_Beamos")
Child_Shadow_Temple_Huge_Pit = OOTLocation.new("Child_Shadow_Temple_Huge_Pit")
Child_Shadow_Temple_Invisible_Spikes = OOTLocation.new("Child_Shadow_Temple_Invisible_Spikes")
Child_Shadow_Temple_Wind_Tunnel = OOTLocation.new("Child_Shadow_Temple_Wind_Tunnel")
Child_Shadow_Temple_After_Wind = OOTLocation.new("Child_Shadow_Temple_After_Wind")
Child_Shadow_Temple_Boat = OOTLocation.new("Child_Shadow_Temple_Boat")
Child_Shadow_Temple_Beyond_Boat = OOTLocation.new("Child_Shadow_Temple_Beyond_Boat")
Child_Shadow_Temple_3_Spinning_Pots_Rupees = OOTLocation.new("Child_Shadow_Temple_3_Spinning_Pots_Rupees")
Child_Shadow_Temple_Beyond_Boat_Scarecrow = OOTLocation.new("Child_Shadow_Temple_Beyond_Boat_Scarecrow")
Child_Shadow_Temple_Beyond_Boat_SoT_Block = OOTLocation.new("Child_Shadow_Temple_Beyond_Boat_SoT_Block")
Child_Shadow_Temple_Before_Boss = OOTLocation.new("Child_Shadow_Temple_Before_Boss")

Adult_Shadow_Temple_Entryway = OOTLocation.new("Adult_Shadow_Temple_Entryway")
Adult_Shadow_Temple_Beginning = OOTLocation.new("Adult_Shadow_Temple_Beginning")
Adult_Shadow_Temple_First_Beamos = OOTLocation.new("Adult_Shadow_Temple_First_Beamos")
Adult_Shadow_Temple_Huge_Pit = OOTLocation.new("Adult_Shadow_Temple_Huge_Pit")
Adult_Shadow_Temple_Invisible_Spikes = OOTLocation.new("Adult_Shadow_Temple_Invisible_Spikes")
Adult_Shadow_Temple_Wind_Tunnel = OOTLocation.new("Adult_Shadow_Temple_Wind_Tunnel")
Adult_Shadow_Temple_After_Wind = OOTLocation.new("Adult_Shadow_Temple_After_Wind")
Adult_Shadow_Temple_Boat = OOTLocation.new("Adult_Shadow_Temple_Boat")
Adult_Shadow_Temple_Beyond_Boat = OOTLocation.new("Adult_Shadow_Temple_Beyond_Boat")
Adult_Shadow_Temple_3_Spinning_Pots_Rupees = OOTLocation.new("Adult_Shadow_Temple_3_Spinning_Pots_Rupees")
Adult_Shadow_Temple_Beyond_Boat_Scarecrow = OOTLocation.new("Adult_Shadow_Temple_Beyond_Boat_Scarecrow")
Adult_Shadow_Temple_Beyond_Boat_SoT_Block = OOTLocation.new("Adult_Shadow_Temple_Beyond_Boat_SoT_Block")
Adult_Shadow_Temple_Before_Boss = OOTLocation.new("Adult_Shadow_Temple_Before_Boss")

-- SpiritTemple

Child_Spirit_Temple_Lobby = OOTLocation.new("Child_Spirit_Temple_Lobby")
Child_Child_Spirit_Temple = OOTLocation.new("Child_Child_Spirit_Temple")
Child_Child_Spirit_Before_Locked_Door = OOTLocation.new("Child_Child_Spirit_Before_Locked_Door")
Child_Early_Adult_Spirit_Temple = OOTLocation.new("Child_Early_Adult_Spirit_Temple")
Child_Child_Spirit_Temple_Climb = OOTLocation.new("Child_Child_Spirit_Temple_Climb")
Child_Spirit_Temple_Central_Chamber = OOTLocation.new("Child_Spirit_Temple_Central_Chamber")
Child_Adult_Spirit_Temple_Climb = OOTLocation.new("Child_Adult_Spirit_Temple_Climb")
Child_Spirit_Temple_Anubis_Room = OOTLocation.new("Child_Spirit_Temple_Anubis_Room")
Child_Spirit_Temple_Beyond_Anubis_Room = OOTLocation.new("Child_Spirit_Temple_Beyond_Anubis_Room")
Child_Spirit_Temple_Big_Mirror_Room = OOTLocation.new("Child_Spirit_Temple_Big_Mirror_Room")

Adult_Spirit_Temple_Lobby = OOTLocation.new("Adult_Spirit_Temple_Lobby")
Adult_Child_Spirit_Temple = OOTLocation.new("Adult_Child_Spirit_Temple")
Adult_Child_Spirit_Before_Locked_Door = OOTLocation.new("Adult_Child_Spirit_Before_Locked_Door")
Adult_Early_Adult_Spirit_Temple = OOTLocation.new("Adult_Early_Adult_Spirit_Temple")
Adult_Child_Spirit_Temple_Climb = OOTLocation.new("Adult_Child_Spirit_Temple_Climb")
Adult_Spirit_Temple_Central_Chamber = OOTLocation.new("Adult_Spirit_Temple_Central_Chamber")
Adult_Adult_Spirit_Temple_Climb = OOTLocation.new("Adult_Adult_Spirit_Temple_Climb")
Adult_Spirit_Temple_Anubis_Room = OOTLocation.new("Adult_Spirit_Temple_Anubis_Room")
Adult_Spirit_Temple_Beyond_Anubis_Room = OOTLocation.new("Adult_Spirit_Temple_Beyond_Anubis_Room")
Adult_Spirit_Temple_Big_Mirror_Room = OOTLocation.new("Adult_Spirit_Temple_Big_Mirror_Room")

-- WT

Child_Water_Temple_Lobby = OOTLocation.new("Child_Water_Temple_Lobby")
Child_Water_Temple_Dive = OOTLocation.new("Child_Water_Temple_Dive")
Child_Water_Temple_Lowered_Water_Levels = OOTLocation.new("Child_Water_Temple_Lowered_Water_Levels")
Child_Water_Temple_South_Basement = OOTLocation.new("Child_Water_Temple_South_Basement")
Child_Water_Temple_Middle_Water_Level = OOTLocation.new("Child_Water_Temple_Middle_Water_Level")
Child_Water_Temple_Cracked_Wall = OOTLocation.new("Child_Water_Temple_Cracked_Wall")
Child_Water_Temple_Central_Bow_Target = OOTLocation.new("Child_Water_Temple_Central_Bow_Target")
Child_Water_Temple_North_Basement = OOTLocation.new("Child_Water_Temple_North_Basement")
Child_Water_Temple_Boss_Key_Chest_Room = OOTLocation.new("Child_Water_Temple_Boss_Key_Chest_Room")
Child_Water_Temple_Falling_Platform_Room = OOTLocation.new("Child_Water_Temple_Falling_Platform_Room")
Child_Water_Temple_Dark_Link_Region = OOTLocation.new("Child_Water_Temple_Dark_Link_Region")
Child_Water_Temple_River = OOTLocation.new("Child_Water_Temple_River")
Child_Water_Temple_Dragon_Statue = OOTLocation.new("Child_Water_Temple_Dragon_Statue")

Adult_Water_Temple_Lobby = OOTLocation.new("Adult_Water_Temple_Lobby")
Adult_Water_Temple_Dive = OOTLocation.new("Adult_Water_Temple_Dive")
Adult_Water_Temple_Lowered_Water_Levels = OOTLocation.new("Adult_Water_Temple_Lowered_Water_Levels")
Adult_Water_Temple_South_Basement = OOTLocation.new("Adult_Water_Temple_South_Basement")
Adult_Water_Temple_Middle_Water_Level = OOTLocation.new("Adult_Water_Temple_Middle_Water_Level")
Adult_Water_Temple_Cracked_Wall = OOTLocation.new("Adult_Water_Temple_Cracked_Wall")
Adult_Water_Temple_Central_Bow_Target = OOTLocation.new("Adult_Water_Temple_Central_Bow_Target")
Adult_Water_Temple_North_Basement = OOTLocation.new("Adult_Water_Temple_North_Basement")
Adult_Water_Temple_Boss_Key_Chest_Room = OOTLocation.new("Adult_Water_Temple_Boss_Key_Chest_Room")
Adult_Water_Temple_Falling_Platform_Room = OOTLocation.new("Adult_Water_Temple_Falling_Platform_Room")
Adult_Water_Temple_Dark_Link_Region = OOTLocation.new("Adult_Water_Temple_Dark_Link_Region")
Adult_Water_Temple_River = OOTLocation.new("Adult_Water_Temple_River")
Adult_Water_Temple_Dragon_Statue = OOTLocation.new("Adult_Water_Temple_Dragon_Statue")

-- bosses

Child_Deku_Tree_Boss_Door = OOTLocation.new("Child_Deku_Tree_Boss_Door")
Child_Queen_Gohma_Boss_Room = OOTLocation.new("Child_Queen_Gohma_Boss_Room")
Child_Dodongos_Cavern_Boss_Door = OOTLocation.new("Child_Dodongos_Cavern_Boss_Door")
Child_King_Dodongo_Boss_Room = OOTLocation.new("Child_King_Dodongo_Boss_Room")
Child_Jabu_Jabus_Belly_Boss_Door = OOTLocation.new("Child_Jabu_Jabus_Belly_Boss_Door")
Child_Barinade_Boss_Room = OOTLocation.new("Child_Barinade_Boss_Room")
Child_Forest_Temple_Boss_Door = OOTLocation.new("Child_Forest_Temple_Boss_Door")
Child_Phantom_Ganon_Boss_Room = OOTLocation.new("Child_Phantom_Ganon_Boss_Room")
Child_Fire_Temple_Boss_Door = OOTLocation.new("Child_Fire_Temple_Boss_Door")
Child_Volvagia_Boss_Room = OOTLocation.new("Child_Volvagia_Boss_Room")
Child_Water_Temple_Boss_Door = OOTLocation.new("Child_Water_Temple_Boss_Door")
Child_Morpha_Boss_Room = OOTLocation.new("Child_Morpha_Boss_Room")
Child_Shadow_Temple_Boss_Door = OOTLocation.new("Child_Shadow_Temple_Boss_Door")
Child_Bongo_Bongo_Boss_Room = OOTLocation.new("Child_Bongo_Bongo_Boss_Room")
Child_Spirit_Temple_Boss_Door = OOTLocation.new("Child_Spirit_Temple_Boss_Door")
Child_Twinrova_Boss_Room = OOTLocation.new("Child_Twinrova_Boss_Room")
Child_Ganons_Castle_Tower = OOTLocation.new("Child_Ganons_Castle_Tower")
Child_Ganons_Castle_Tower_Below_Boss = OOTLocation.new("Child_Ganons_Castle_Tower_Below_Boss")
Child_Ganondorf_Boss_Room = OOTLocation.new("Child_Ganondorf_Boss_Room")

Adult_Deku_Tree_Boss_Door = OOTLocation.new("Adult_Deku_Tree_Boss_Door")
Adult_Queen_Gohma_Boss_Room = OOTLocation.new("Adult_Queen_Gohma_Boss_Room")
Adult_Dodongos_Cavern_Boss_Door = OOTLocation.new("Adult_Dodongos_Cavern_Boss_Door")
Adult_King_Dodongo_Boss_Room = OOTLocation.new("Adult_King_Dodongo_Boss_Room")
Adult_Jabu_Jabus_Belly_Boss_Door = OOTLocation.new("Adult_Jabu_Jabus_Belly_Boss_Door")
Adult_Barinade_Boss_Room = OOTLocation.new("Adult_Barinade_Boss_Room")
Adult_Forest_Temple_Boss_Door = OOTLocation.new("Adult_Forest_Temple_Boss_Door")
Adult_Phantom_Ganon_Boss_Room = OOTLocation.new("Adult_Phantom_Ganon_Boss_Room")
Adult_Fire_Temple_Boss_Door = OOTLocation.new("Adult_Fire_Temple_Boss_Door")
Adult_Volvagia_Boss_Room = OOTLocation.new("Adult_Volvagia_Boss_Room")
Adult_Water_Temple_Boss_Door = OOTLocation.new("Adult_Water_Temple_Boss_Door")
Adult_Morpha_Boss_Room = OOTLocation.new("Adult_Morpha_Boss_Room")
Adult_Shadow_Temple_Boss_Door = OOTLocation.new("Adult_Shadow_Temple_Boss_Door")
Adult_Bongo_Bongo_Boss_Room = OOTLocation.new("Adult_Bongo_Bongo_Boss_Room")
Adult_Spirit_Temple_Boss_Door = OOTLocation.new("Adult_Spirit_Temple_Boss_Door")
Adult_Twinrova_Boss_Room = OOTLocation.new("Adult_Twinrova_Boss_Room")
Adult_Ganons_Castle_Tower = OOTLocation.new("Adult_Ganons_Castle_Tower")
Adult_Ganons_Castle_Tower_Below_Boss = OOTLocation.new("Adult_Ganons_Castle_Tower_Below_Boss")
Adult_Ganondorf_Boss_Room = OOTLocation.new("Adult_Ganondorf_Boss_Room")

--warps
Child_Prelude_of_Light_Warp = OOTLocation.new("Child_Prelude_of_Light_Warp")
Child_Minuet_of_Forest_Warp = OOTLocation.new("Child_Minuet_of_Forest_Warp")
Child_Bolero_of_Fire_Warp = OOTLocation.new("Child_Bolero_of_Fire_Warp")
Child_Serenade_of_Water_Warp = OOTLocation.new("Child_Serenade_of_Water_Warp")
Child_Nocturne_of_Shadow_Warp = OOTLocation.new("Child_Nocturne_of_Shadow_Warp")
Child_Requiem_of_Spirit_Warp = OOTLocation.new("Child_Requiem_of_Spirit_Warp")

Adult_Prelude_of_Light_Warp = OOTLocation.new("Adult_Prelude_of_Light_Warp")
Adult_Minuet_of_Forest_Warp = OOTLocation.new("Adult_Minuet_of_Forest_Warp")
Adult_Bolero_of_Fire_Warp = OOTLocation.new("Adult_Bolero_of_Fire_Warp")
Adult_Serenade_of_Water_Warp = OOTLocation.new("Adult_Serenade_of_Water_Warp")
Adult_Nocturne_of_Shadow_Warp = OOTLocation.new("Adult_Nocturne_of_Shadow_Warp")
Adult_Requiem_of_Spirit_Warp = OOTLocation.new("Adult_Requiem_of_Spirit_Warp")











-- Child_Hyrule_Fields = OOTLocation.new("Child_Hyrule_Fields")
-- Child_Lon_Lon_Ranch = OOTLocation.new("Child_Lon_Lon_Ranch")
-- Child_Lost_Woods = OOTLocation.new("Child_Lost_Woods")
-- Child_Kokiri_Forest = OOTLocation.new("Child_Kokiri_Forest")
-- Child_Deku_Tree = OOTLocation.new("Child_Deku_Tree")
-- Child_Sacret_Forest_Meadow = OOTLocation.new("Child_Sacret_Forest_Meadow")
-- Child_Lake_Hylia = OOTLocation.new("Child_Lake_Hylia")
-- Child_Market = OOTLocation.new("Child_Market")
-- Child_Temple_of_time = OOTLocation.new("Child_Temple_of_time")
-- Child_Hyrule_Castle = OOTLocation.new("Child_Hyrule_Castle")
-- Child_Gerudo_Valley = OOTLocation.new("Child_Gerudo_Valley")
-- Child_Gerudo_Fortress = OOTLocation.new("Child_Gerudo_Fortress")
-- Child_Wastelands = OOTLocation.new("Child_Wastelands")
-- Child_Dessert_Colossus = OOTLocation.new("Child_Dessert_Colossus")
-- Child_Spirit_Temple = OOTLocation.new("Child_Spirit_Temple")
-- Child_Zora_River = OOTLocation.new("Child_Zora_River")
-- Child_Zora_Fountain = OOTLocation.new("Child_Zora_Fountain")
-- Child_Zora_Domain = OOTLocation.new("Child_Zora_Domain")
-- Child_Lord_Jabu_Jabu = OOTLocation.new("Child_Lord_Jabu_Jabu")
-- Child_Kakariko_Village = OOTLocation.new("Child_Kakariko_Village")
-- Child_Graveyard = OOTLocation.new("Child_Graveyard")
-- Child_Bottom_Of_The_Well = OOTLocation.new("Child_Bottom_Of_The_Well")
-- Child_Death_Mountain_Trail = OOTLocation.new("Child_Death_Mountain_Trail")
-- Child_Death_Mountain_Crater = OOTLocation.new("Child_Death_Mountain_Crater")
-- Child_Goron_City = OOTLocation.new("Child_Goron_City")
-- Child_Dodongos_Cavern = OOTLocation.new("Child_Dodongos_Cavern")

-- Adult_Hyrule_Fields = OOTLocation.new("Adult_Hyrule_Fields")
-- Adult_Lon_Lon_Ranch = OOTLocation.new("Adult_Lon_Lon_Ranch")
-- Adult_Lost_Woods = OOTLocation.new("Adult_Lost_Woods")
-- Adult_Kokiri_Forest = OOTLocation.new("Adult_Kokiri_Forest")
-- Adult_Sacret_Forest_Meadow = OOTLocation.new("Adult_Sacret_Forest_Meadow")
-- Adult_Forest_Temple = OOTLocation.new("Adult_Forest_Temple")
-- Adult_Lake_Hylia = OOTLocation.new("Adult_Lake_Hylia")
-- Adult_Water_Temple = OOTLocation.new("Adult_Water_Temple")
-- Adult_Market = OOTLocation.new("Adult_Market")
-- Adult_Temple_of_time = OOTLocation.new("Adult_Temple_of_time")
-- Adult_Hyrule_Castle = OOTLocation.new("Adult_Hyrule_Castle")
-- Adult_Gerudo_Valley = OOTLocation.new("Adult_Gerudo_Valley")
-- Adult_Gerudo_Fortress = OOTLocation.new("Adult_Gerudo_Fortress")
-- Adult_Gerudo_hideout = OOTLocation.new("Adult_Gerudo_hideout")
-- Adult_Gerudo_training_ground = OOTLocation.new("Adult_Gerudo_training_ground")
-- Adult_Wastelands = OOTLocation.new("Adult_Wastelands")
-- Adult_Dessert_Colossus = OOTLocation.new("Adult_Dessert_Colossus")
-- Adult_Spirit_Temple = OOTLocation.new("Adult_Spirit_Temple")
-- Adult_Zora_River = OOTLocation.new("Adult_Zora_River")
-- Adult_Zora_Fountain = OOTLocation.new("Adult_Zora_Fountain")
-- Adult_Zora_Domain = OOTLocation.new("Adult_Zora_Domain")
-- Adult_Ice_Cavern = OOTLocation.new("Adult_Ice_Cavern")
-- Adult_Kakariko_Village = OOTLocation.new("Adult_Kakariko_Village")
-- Adult_Graveyard = OOTLocation.new("Adult_Graveyard")
-- Adult_Shadow_Temple = OOTLocation.new("Adult_Shadow_Temple")
-- Adult_Bottom_Of_The_Well = OOTLocation.new("Adult_Bottom_Of_The_Well")
-- Adult_Death_Mountain_Trail = OOTLocation.new("Adult_Death_Mountain_Trail")
-- Adult_Death_Mountain_Crater = OOTLocation.new("Adult_Death_Mountain_Crater")
-- Adult_Goron_City = OOTLocation.new("Adult_Goron_City")
-- Adult_Fire_Temple = OOTLocation.new("Adult_Fire_Temple")
-- Adult_Dodongos_Cavern = OOTLocation.new("Adult_Dodongos_Cavern")
-- Adult_Ganons_Tower = OOTLocation.new("Adult_Ganons_Tower")
-- Adult_Ganons_Castle = OOTLocation.new("Adult_Ganons_Castle")

-- -- -- child


-- Child_Kokiri_Forest:connect_one_way(Child_Deku_Tree)
-- Child_Kokiri_Forest:connect_one_way(Child_Lost_Woods)

-- Child_Deku_Tree:connect_one_way(Child_Kokiri_Forest)

-- Child_Lost_Woods:connect_one_way(Child_Hyrule_Fields)
-- Child_Lost_Woods:connect_one_way(Child_Kokiri_Forest)

-- Child_Hyrule_Fields:connect_one_way(Child_Market)
-- Child_Hyrule_Fields:connect_one_way(Child_Lost_Woods)
-- Child_Hyrule_Fields:connect_one_way(Child_Lon_Lon_Ranch)
-- Child_Hyrule_Fields:connect_one_way(Child_Lake_Hylia)
-- Child_Hyrule_Fields:connect_one_way(Child_Gerudo_Valley)
-- Child_Hyrule_Fields:connect_one_way(Child_Kakariko_Village)
-- Child_Hyrule_Fields:connect_one_way(Child_Zora_River)

-- Child_Lon_Lon_Ranch:connect_one_way(Child_Hyrule_Fields)

-- Child_Lake_Hylia:connect_one_way(Child_Hyrule_Fields)

-- Child_Gerudo_Valley:connect_one_way(Child_Hyrule_Fields)

-- Child_Wastelands:connect_one_way(Child_Dessert_Colossus)

-- Child_Dessert_Colossus:connect_one_way(Child_Wastelands)
-- Child_Dessert_Colossus:connect_one_way(Child_Spirit_Temple)

-- Child_Kakariko_Village:connect_one_way(Child_Hyrule_Fields)
-- Child_Kakariko_Village:connect_one_way(Child_Graveyard)
-- Child_Kakariko_Village:connect_one_way(Child_Death_Mountain_Trail)

-- Child_Graveyard:connect_one_way(Child_Kakariko_Village)

-- Child_Death_Mountain_Trail:connect_one_way(Child_Kakariko_Village)
-- Child_Death_Mountain_Trail:connect_one_way(Child_Death_Mountain_Crater)

-- Child_Death_Mountain_Crater:connect_one_way(Child_Death_Mountain_Trail)
-- Child_Death_Mountain_Crater:connect_one_way(Child_Goron_City)

-- Child_Goron_City:connect_one_way(Child_Death_Mountain_Crater)
-- Child_Goron_City:connect_one_way(Child_Dodongos_Cavern)

-- Child_Zora_River:connect_one_way(Child_Hyrule_Fields)
-- Child_Zora_River:connect_one_way(Child_Zora_Fountain)

-- Child_Zora_Fountain:connect_one_way(Child_Zora_River)
-- Child_Zora_Fountain:connect_one_way(Child_Zora_Domain)

-- Child_Zora_Domain:connect_one_way(Child_Zora_Fountain)
-- Child_Zora_Domain:connect_one_way(Child_Lord_Jabu_Jabu)

-- Child_Lord_Jabu_Jabu:connect_one_way(Child_Zora_Domain)

-- Child_Market:connect_one_way(Child_Hyrule_Fields)
-- Child_Market:connect_one_way(Child_Temple_of_time)
-- Child_Market:connect_one_way(Child_Hyrule_Castle)

-- Child_Hyrule_Castle:connect_one_way(Child_Market)

-- Adult_Temple_of_time:connect_one_way(Child_Market)
-- Adult_Temple_of_time:connect_one_way(Adult_Temple_of_time)



-- -- adult

-- Adult_Kokiri_Forest:connect_one_way(Adult_Lost_Woods)

-- Adult_Lost_Woods:connect_one_way(Adult_Hyrule_Fields)
-- Adult_Lost_Woods:connect_one_way(Adult_Kokiri_Forest)
-- Adult_Lost_Woods:connect_one_way(Adult_Sacret_Forest_Meadow)

-- Adult_Sacret_Forest_Meadow:connect_one_way(Adult_Lost_Woods)
-- Adult_Sacret_Forest_Meadow:connect_one_way(Adult_Forest_Temple)

-- Adult_Forest_Temple:connect_one_way(Adult_Sacret_Forest_Meadow)

-- Adult_Hyrule_Fields:connect_one_way(Adult_Market)
-- Adult_Hyrule_Fields:connect_one_way(Adult_Lost_Woods)
-- Adult_Hyrule_Fields:connect_one_way(Adult_Lon_Lon_Ranch)
-- Adult_Hyrule_Fields:connect_one_way(Adult_Lake_Hylia)
-- Adult_Hyrule_Fields:connect_one_way(Adult_Gerudo_Valley)
-- Adult_Hyrule_Fields:connect_one_way(Adult_Kakariko_Village)
-- Adult_Hyrule_Fields:connect_one_way(Adult_Zora_River)

-- Adult_Lon_Lon_Ranch:connect_one_way(Adult_Hyrule_Fields)

-- Adult_Lake_Hylia:connect_one_way(Adult_Hyrule_Fields)
-- Adult_Lake_Hylia:connect_one_way(Adult_Water_Temple)

-- Adult_Water_Temple:connect_one_way(Adult_Lake_Hylia)

-- Adult_Gerudo_Valley:connect_one_way(Adult_Hyrule_Fields)
-- Adult_Gerudo_Valley:connect_one_way(Adult_Gerudo_training_ground)

-- Adult_Gerudo_training_ground:connect_one_way(Adult_Gerudo_Valley)
-- Adult_Gerudo_training_ground:connect_one_way(Adult_Wastelands)

-- Adult_Wastelands:connect_one_way(Adult_Gerudo_training_ground)
-- Adult_Wastelands:connect_one_way(Adult_Dessert_Colossus)

-- Adult_Dessert_Colossus:connect_one_way(Adult_Wastelands)
-- Adult_Dessert_Colossus:connect_one_way(Adult_Spirit_Temple)

-- Adult_Kakariko_Village:connect_one_way(Adult_Hyrule_Fields)
-- Adult_Kakariko_Village:connect_one_way(Adult_Graveyard)
-- Adult_Kakariko_Village:connect_one_way(Adult_Death_Mountain_Trail)
-- Adult_Kakariko_Village:connect_one_way(Adult_Bottom_Of_The_Well)

-- Adult_Bottom_Of_The_Well:connect_one_way(Adult_Kakariko_Village)

-- Adult_Graveyard:connect_one_way(Adult_Kakariko_Village)
-- Adult_Graveyard:connect_one_way(Adult_Shadow_Temple)

-- Adult_Shadow_Temple:connect_one_way(Adult_Graveyard)

-- Adult_Death_Mountain_Trail:connect_one_way(Adult_Kakariko_Village)
-- Adult_Death_Mountain_Trail:connect_one_way(Adult_Death_Mountain_Crater)

-- Adult_Death_Mountain_Crater:connect_one_way(Adult_Death_Mountain_Trail)
-- Adult_Death_Mountain_Crater:connect_one_way(Adult_Goron_City)
-- Adult_Death_Mountain_Crater:connect_one_way(Adult_Fire_Temple)

-- Adult_Fire_Temple:connect_one_way(Adult_Death_Mountain_Crater)

-- Adult_Goron_City:connect_one_way(Adult_Death_Mountain_Crater)

-- Adult_Zora_River:connect_one_way(Adult_Hyrule_Fields)
-- Adult_Zora_River:connect_one_way(Adult_Zora_Fountain)

-- Adult_Zora_Fountain:connect_one_way(Adult_Zora_River)
-- Adult_Zora_Fountain:connect_one_way(Adult_Zora_Domain)

-- Adult_Zora_Domain:connect_one_way(Adult_Zora_Fountain)
-- Adult_Zora_Domain:connect_one_way(Adult_Ice_Cavern)

-- Adult_Ice_Cavern:connect_one_way(Adult_Zora_Domain)

-- Adult_Market:connect_one_way(Adult_Hyrule_Fields)
-- Adult_Market:connect_one_way(Adult_Temple_of_time)
-- Adult_Market:connect_one_way(Adult_Ganons_Castle)

-- Adult_Ganons_Castle:connect_one_way(Adult_Market)
-- Adult_Ganons_Castle:connect_one_way(Adult_Ganons_Tower)

-- Adult_Ganons_Tower:connect_one_way(Adult_Ganons_Castle)

-- Adult_Temple_of_time:connect_one_way(Adult_Market)
-- Adult_Temple_of_time:connect_one_way(Child_Temple_of_time)

-- entry_point = OOTLocation.new("entry_point")
-- child_spawn = OOTLocation.new("child_spawns")
-- adult_spawn = OOTLocation.new("adult_spawn")

-- entry_point:connect_one_way_entrance("Child Spawn", child_spawn)--, function() return openOrStandard() end)
-- entry_point:connect_one_way_entrance("Child Spawn", adult_spawn)--, function() return inverted() end)

-- child_spawn:connect_one_way_entrance("Child Spawn in Game", Child_Links_House)
-- adult_spawn:connect_one_way_entrance("Adult Spawn in Game", Adult_Temple_of_Time)
Child_spawn:connect_one_way_entrance("Child Spawn in Game", Child_Links_House)
Adult_spawn:connect_one_way_entrance("Adult Spawn in Game", Adult_Temple_of_Time)


Entry_point:connect_one_way_entrance("Child Spawn", Child_spawn, function() return Tracker:FindObjectForCode("starting_age").Active == false end)--, function() return openOrStandard() end)
Entry_point:connect_one_way_entrance("Adult Spawn", Adult_spawn, function() return Tracker:FindObjectForCode("starting_age").Active == true end)--, function() return inverted() end)

Entry_point:connect_one_way_entrance("Child Prelude of Light Warp", Child_Prelude_of_Light_Warp, function() return All(Can_play("PreludeofLight"), Can_leave_forest("child")) end)
Entry_point:connect_one_way_entrance("Child Minuet of Forest Warp", Child_Minuet_of_Forest_Warp, function() return Can_play("MinuetofForest") end)
Entry_point:connect_one_way_entrance("Child Bolero of Fire Warp", Child_Bolero_of_Fire_Warp, function() return All(Can_play("BoleroofFire"), Can_leave_forest("child")) end)
Entry_point:connect_one_way_entrance("Child Serenade of Water Warp", Child_Serenade_of_Water_Warp, function() return All(Can_play("SerenadeofWater"), Can_leave_forest("child")) end)
Entry_point:connect_one_way_entrance("Child Nocturne of Shadow Warp", Child_Nocturne_of_Shadow_Warp, function() return All(Can_play("NocturneofShadow"), Can_leave_forest("child")) end)
Entry_point:connect_one_way_entrance("Child Requiem of Spirit Warp", Child_Requiem_of_Spirit_Warp, function() return All(Can_play("RequiemofSpirit"), Can_leave_forest("child")) end)
Entry_point:connect_one_way_entrance("Adult Prelude of Light Warp", Adult_Prelude_of_Light_Warp, function() return All(Can_play("PreludeofLight"), Can_leave_forest("adult")) end)
Entry_point:connect_one_way_entrance("Adult Minuet of Forest Warp", Adult_Minuet_of_Forest_Warp, function() return Can_play("MinuetofForest") end)
Entry_point:connect_one_way_entrance("Adult Bolero of Fire Warp", Adult_Bolero_of_Fire_Warp, function() return All(Can_play("BoleroofFire"), Can_leave_forest("adult")) end)
Entry_point:connect_one_way_entrance("Adult Serenade of Water Warp", Adult_Serenade_of_Water_Warp, function() return All(Can_play("SerenadeofWater"), Can_leave_forest("adult")) end)
Entry_point:connect_one_way_entrance("Adult Nocturne of Shadow Warp", Adult_Nocturne_of_Shadow_Warp, function() return All(Can_play("NocturneofShadow"), Can_leave_forest("adult")) end)
Entry_point:connect_one_way_entrance("Adult Requiem of Spirit Warp", Adult_Requiem_of_Spirit_Warp, function() return All(Can_play("RequiemofSpirit"), Can_leave_forest("adult")) end)

-- Entry_point:connect_one_way_entrance("Child Spawn", Child_spawn, function() return Tracker:FindObjectForCode("starting_age").Active == false end)--, function() return openOrStandard() end)
-- Entry_point:connect_one_way_entrance("Adult Spawn", Adult_spawn, function() return Tracker:FindObjectForCode("starting_age").Active == true end)--, function() return inverted() end)


Child_Prelude_of_Light_Warp:connect_one_way_entrance("Child Temple of Time", Child_Temple_of_Time)
Adult_Prelude_of_Light_Warp:connect_one_way_entrance("Adult Temple of Time", Adult_Temple_of_Time)

Child_Minuet_of_Forest_Warp:connect_one_way_entrance("Child Sacred Forest Meadow", Child_Sacret_Forest_Meadow)
Adult_Minuet_of_Forest_Warp:connect_one_way_entrance("Adult Sacred Forest Meadow", Adult_Sacret_Forest_Meadow)

Child_Bolero_of_Fire_Warp:connect_one_way_entrance("Child DMC Central Local", Child_DMC_Central_Local)
Adult_Bolero_of_Fire_Warp:connect_one_way_entrance("Adult DMC Central Local", Adult_DMC_Central_Local)

Child_Serenade_of_Water_Warp:connect_one_way_entrance("Child Lake Hylia", Child_Lake_Hylia)
Adult_Serenade_of_Water_Warp:connect_one_way_entrance("Adult Lake Hylia", Adult_Lake_Hylia)

Child_Nocturne_of_Shadow_Warp:connect_one_way_entrance("Child Graveyard Warp Pad Region", Child_Graveyard_Warp_Pad_Region)
Adult_Nocturne_of_Shadow_Warp:connect_one_way_entrance("Adult Graveyard Warp Pad Region", Adult_Graveyard_Warp_Pad_Region)

Child_Requiem_of_Spirit_Warp:connect_one_way_entrance("Child Desert Colossus", Child_Desert_Colossus)
Adult_Requiem_of_Spirit_Warp:connect_one_way_entrance("Adult Desert Colossus", Adult_Desert_Colossus)