Tracker:AddLayouts("layouts/events.jsonc")
Tracker:AddLayouts("layouts/settings_popup.jsonc")
Tracker:AddLayouts("layouts/settings.jsonc")
Tracker:AddLayouts("layouts/logictricks.jsonc")
Tracker:AddLayouts("layouts/items.jsonc")
Tracker:AddLayouts("layouts/tabs.jsonc")
Tracker:AddLayouts("layouts/tracker.jsonc")
Tracker:AddLayouts("layouts/broadcast.jsonc")
Tracker:AddLayouts("layouts/dungeon_items.jsonc")
Tracker:AddLayouts("layouts/dungeons.jsonc")
Tracker:AddLayouts("layouts/songs_medallions.jsonc")
-- Tracker:AddLayouts("layouts/dungeon_items_keydrop.jsonc")

Tracker:AddLayouts("layouts/Shadow_Temple.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Shadow_Temple.jsonc")
Tracker:AddLayouts("layouts/Dodongos_Cavern.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Dodongos_Cavern.jsonc")
Tracker:AddLayouts("layouts/Bottom_of_the_Well.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Bottom_of_the_Well.jsonc")
Tracker:AddLayouts("layouts/Ganons_Castle.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Ganons_Castle.jsonc")
Tracker:AddLayouts("layouts/Ice_Cavern.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Ice_Cavern.jsonc")
Tracker:AddLayouts("layouts/Spirit_Temple.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Spirit_Temple.jsonc")
Tracker:AddLayouts("layouts/Ganons_Tower.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Ganons_Tower.jsonc")
Tracker:AddLayouts("layouts/Fire_Temple.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Fire_Temple.jsonc")
Tracker:AddLayouts("layouts/Jabu_Jabus_Belly.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Jabu_Jabus_Belly.jsonc")
Tracker:AddLayouts("layouts/Gerudo_Training_Ground.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Gerudo_Training_Ground.jsonc")
Tracker:AddLayouts("layouts/Forest_Temple.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Forest_Temple.jsonc")
Tracker:AddLayouts("layouts/Deku_Tree.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Deku_Tree.jsonc")
Tracker:AddLayouts("layouts/Water_Temple.jsonc")
-- Tracker:AddLayouts("layouts/MQ_Water_Temple.jsonc")