Tracker:AddLayouts("layouts/events.jsonc")
Tracker:AddLayouts("layouts/settings_popup.jsonc")
Tracker:AddLayouts("layouts/settings.jsonc")
Tracker:AddLayouts("layouts/logictricks.jsonc")
Tracker:AddLayouts("layouts/items.jsonc")
Tracker:AddLayouts("layouts/tabs.jsonc")
Tracker:AddLayouts("layouts/tracker.jsonc")
Tracker:AddLayouts("layouts/broadcast.jsonc")
Tracker:AddLayouts("layouts/dungeon_items.jsonc")
-- Tracker:AddLayouts("layouts/dungeon_items_keydrop.jsonc")