Tracker:AddLocations("locations/Shadow Temple.jsonc")
Tracker:AddLocations("locations/LH.jsonc")
Tracker:AddLocations("locations/HC.jsonc")
Tracker:AddLocations("locations/Hideout.jsonc")
Tracker:AddLocations("locations/Wasteland.jsonc")
Tracker:AddLocations("locations/Dodongos Cavern.jsonc")
Tracker:AddLocations("locations/SFM.jsonc")
Tracker:AddLocations("locations/Bottom of the Well.jsonc")
Tracker:AddLocations("locations/Ganons Castle.jsonc")
Tracker:AddLocations("locations/ZD.jsonc")
Tracker:AddLocations("locations/DMC.jsonc")
Tracker:AddLocations("locations/KV.jsonc")
Tracker:AddLocations("locations/GC.jsonc")
Tracker:AddLocations("locations/Ice Cavern.jsonc")
Tracker:AddLocations("locations/ZR.jsonc")
Tracker:AddLocations("locations/Spirit Temple.jsonc")
Tracker:AddLocations("locations/Ganons Tower.jsonc")
Tracker:AddLocations("locations/DMT.jsonc")
Tracker:AddLocations("locations/Fire Temple.jsonc")
Tracker:AddLocations("locations/Market.jsonc")
Tracker:AddLocations("locations/Graveyard.jsonc")
Tracker:AddLocations("locations/ZF.jsonc")
Tracker:AddLocations("locations/HF.jsonc")
Tracker:AddLocations("locations/Jabu Jabus Belly.jsonc")
Tracker:AddLocations("locations/Gerudo Training Ground.jsonc")
Tracker:AddLocations("locations/Colossus.jsonc")
Tracker:AddLocations("locations/LW.jsonc")
Tracker:AddLocations("locations/GV.jsonc")
Tracker:AddLocations("locations/GF.jsonc")
Tracker:AddLocations("locations/Forest Temple.jsonc")
Tracker:AddLocations("locations/Deku Tree.jsonc")
Tracker:AddLocations("locations/Kak.jsonc")
Tracker:AddLocations("locations/Water Temple.jsonc")
Tracker:AddLocations("locations/LLR.jsonc")
Tracker:AddLocations("locations/ToT.jsonc")
Tracker:AddLocations("locations/Gift from Sages.jsonc")
Tracker:AddLocations("locations/KF.jsonc")
Tracker:AddLocations("locations/Overworld.jsonc")
