Tracker:AddLocations("locations/Gerudo Training Ground.json")
Tracker:AddLocations("locations/Gift from Sages.json")
Tracker:AddLocations("locations/GV.json")
Tracker:AddLocations("locations/SFM.json")
Tracker:AddLocations("locations/HF.json")
Tracker:AddLocations("locations/Dodongos Cavern.json")
Tracker:AddLocations("locations/Ganons Tower.json")
Tracker:AddLocations("locations/Sheik.json")
Tracker:AddLocations("locations/Hideout.json")
Tracker:AddLocations("locations/Water Temple.json")
Tracker:AddLocations("locations/Spirit Temple.json")
Tracker:AddLocations("locations/GF.json")
Tracker:AddLocations("locations/Ice Cavern.json")
Tracker:AddLocations("locations/LLR.json")
Tracker:AddLocations("locations/Graveyard.json")
Tracker:AddLocations("locations/Ganons Castle.json")
Tracker:AddLocations("locations/Bottom of the Well.json")
Tracker:AddLocations("locations/HC.json")
Tracker:AddLocations("locations/ZD.json")
Tracker:AddLocations("locations/ToT.json")
Tracker:AddLocations("locations/ZF.json")
Tracker:AddLocations("locations/LW.json")
Tracker:AddLocations("locations/Shadow Temple.json")
Tracker:AddLocations("locations/KF.json")
Tracker:AddLocations("locations/Forest Temple.json")
Tracker:AddLocations("locations/LH.json")
Tracker:AddLocations("locations/Jabu Jabus Belly.json")
Tracker:AddLocations("locations/Deku Theater.json")
Tracker:AddLocations("locations/Deku Tree.json")
Tracker:AddLocations("locations/DMT.json")
Tracker:AddLocations("locations/DMC.json")
Tracker:AddLocations("locations/Fire Temple.json")
Tracker:AddLocations("locations/Wasteland.json")
Tracker:AddLocations("locations/Kak.json")
Tracker:AddLocations("locations/Colossus.json")
Tracker:AddLocations("locations/ZR.json")
Tracker:AddLocations("locations/Song.json")
Tracker:AddLocations("locations/GC.json")
Tracker:AddLocations("locations/Market.json")
