Tracker:AddLocations("locations/Shadow Temple.lua")
Tracker:AddLocations("locations/LH.lua")
Tracker:AddLocations("locations/HC.lua")
Tracker:AddLocations("locations/Hideout.lua")
Tracker:AddLocations("locations/Wasteland.lua")
Tracker:AddLocations("locations/Dodongos Cavern.lua")
Tracker:AddLocations("locations/SFM.lua")
Tracker:AddLocations("locations/Bottom of the Well.lua")
Tracker:AddLocations("locations/Ganons Castle.lua")
Tracker:AddLocations("locations/ZD.lua")
Tracker:AddLocations("locations/DMC.lua")
Tracker:AddLocations("locations/KV.lua")
Tracker:AddLocations("locations/GC.lua")
Tracker:AddLocations("locations/Ice Cavern.lua")
Tracker:AddLocations("locations/ZR.lua")
Tracker:AddLocations("locations/Spirit Temple.lua")
Tracker:AddLocations("locations/Ganons Tower.lua")
Tracker:AddLocations("locations/DMT.lua")
Tracker:AddLocations("locations/Fire Temple.lua")
Tracker:AddLocations("locations/Market.lua")
Tracker:AddLocations("locations/Graveyard.lua")
Tracker:AddLocations("locations/ZF.lua")
Tracker:AddLocations("locations/HF.lua")
Tracker:AddLocations("locations/Jabu Jabus Belly.lua")
Tracker:AddLocations("locations/Gerudo Training Ground.lua")
Tracker:AddLocations("locations/Colossus.lua")
Tracker:AddLocations("locations/LW.lua")
Tracker:AddLocations("locations/GV.lua")
Tracker:AddLocations("locations/GF.lua")
Tracker:AddLocations("locations/Forest Temple.lua")
Tracker:AddLocations("locations/Deku Tree.lua")
Tracker:AddLocations("locations/Kak.lua")
Tracker:AddLocations("locations/Water Temple.lua")
Tracker:AddLocations("locations/LLR.lua")
Tracker:AddLocations("locations/ToT.lua")
Tracker:AddLocations("locations/Gift from Sages.lua")
Tracker:AddLocations("locations/KF.lua")
-- Tracker:AddLocations("locations/Overworld.lua")
