require("scripts/logic/Bosses")
require("scripts/logic/LH")
require("scripts/logic/Hideout")
require("scripts/logic/Wasteland")
require("scripts/logic/HC")
require("scripts/logic/SFM")
require("scripts/logic/ZD")
require("scripts/logic/DMC")
require("scripts/logic/KV")
require("scripts/logic/GC")
require("scripts/logic/ZR")
require("scripts/logic/DMT")
require("scripts/logic/Market")
require("scripts/logic/Graveyard")
require("scripts/logic/ZF")
require("scripts/logic/HF")
require("scripts/logic/Colossus")
require("scripts/logic/LW")
require("scripts/logic/GV")
require("scripts/logic/GF")
require("scripts/logic/Kak")
require("scripts/logic/LLR")
require("scripts/logic/ToT")
require("scripts/logic/Gift from Sages")
require("scripts/logic/KF")
-- require("locations/Overworld")

require("scripts/logic/Shadow Temple")
require("scripts/logic/Dodongos Cavern")
require("scripts/logic/Bottom of the Well")
require("scripts/logic/Ganons Castle")
require("scripts/logic/Ice Cavern")
require("scripts/logic/Spirit Temple")
require("scripts/logic/Ganons Tower")
require("scripts/logic/Fire Temple")
require("scripts/logic/Jabu Jabus Belly")
require("scripts/logic/Gerudo Training Ground")
require("scripts/logic/Forest Temple")
require("scripts/logic/Deku Tree")
require("scripts/logic/Water Temple")

-- require("scripts/logic/MQ Shadow Temple")
-- require("scripts/logic/MQ Dodongos Cavern")
-- require("scripts/logic/MQ Bottom of the Well")
-- require("scripts/logic/MQ Ganons Castle")
-- require("scripts/logic/MQ Ice Cavern")
-- require("scripts/logic/MQ Spirit Temple")
-- require("scripts/logic/MQ Ganons Tower")
-- require("scripts/logic/MQ Fire Temple")
-- require("scripts/logic/MQ Jabu Jabus Belly")
-- require("scripts/logic/MQ Gerudo Training Ground")
-- require("scripts/logic/MQ Forest Temple")
-- require("scripts/logic/MQ Deku Tree")
-- require("scripts/logic/MQ Water Temple")

-- print("test")
StaleState()
StateChange()
-- Entry_point:discover(AccessibilityLevel.None, 0)
for index, location in pairs(NamedLocations) do
    location.accessibility_level = 0
end
StaleState()
StateChange()